/**
 * AVISO DE PROPRIEDADE INTELECTUAL
 * * O código deste arquivo (estrutura JSON) é distribuído sob licença MIT.
 * ENTRETANTO, os valores de texto (As descrições da Classificação Decimal de Dewey)
 * são propriedade intelectual da OCLC (Online Computer Library Center).
 * * Estes dados são utilizados neste projeto estritamente para fins 
 * educacionais, de estudo pessoal e referência local (Fair Use).
 * A redistribuição comercial destes dados específicos não é autorizada 
 * pela licença MIT do restante do projeto.
 * * Fonte de referência: OCLC Dewey Summaries.
 */
/* --- BASE CDD (Dewey) --- */
/* --- BASE CDD (Dewey) --- */
const baseCDD = [
    { code: "000", desc: "Generalidades e Ciência da Computação" },
    { code: "001", desc: "Conhecimento e Teoria" },
    { code: "001.4", desc: "Métodos de estudo, Metodologia e Pesquisa" },
    { code: "001.42", desc: "Pesquisa científica" },
    { code: "001.94", desc: "Mistérios e fatos misteriosos" },
    { code: "001.942", desc: "Discos voadores, Óvnis" },
    { code: "001.944", desc: "Monstros e temas relacionados" },
    { code: "002", desc: "O livro" },
    { code: "003", desc: "Sistemas" },
    { code: "004", desc: "Processamento de dados e Ciência da Computação" },
    { code: "004.03", desc: "Dicionário de computação" },
    { code: "004.07", desc: "Computação – Estudo e ensino" },
    { code: "004.6", desc: "Redes de computadores" },
    { code: "004.678", desc: "Internet" },
    { code: "005", desc: "Programação, software e dados" },
    { code: "005.1", desc: "Desenvolvimento de software" },
    { code: "006", desc: "Métodos especiais (IA, Gráficos)" },
    { code: "010", desc: "Bibliografias" },
    { code: "011", desc: "Bibliografias gerais" },
    { code: "012", desc: "Bibliografias e catálogos individuais" },
    { code: "013", desc: "Bibliografias e catálogos de autores por classes específicas" },
    { code: "014", desc: "Bibliografias e catálogos de trabalhos anônimos ou com pseudônimos" },
    { code: "015", desc: "Bibliografia e catálogos de trabalhos de lugares específicos" },
    { code: "016", desc: "Bibliografia e catálogo de trabalhos de assuntos específicos" },
    { code: "016.981", desc: "Bibliografia do Brasil" },
    { code: "017", desc: "Catálogos de bibliotecas privadas, públicas, leilões" },
    { code: "018", desc: "Catálogos arranjados por autor, assunto, data" },
    { code: "019", desc: "Catálogos dicionário, Arquivos e técnicas de arquivo" },
    { code: "020", desc: "Biblioteconomia e Ciência da Informação" },
    { code: "021", desc: "Conexão e relacionamento entre bibliotecas, arquivos e centros" },
    { code: "022", desc: "Administração de planta física" },
    { code: "023", desc: "Administração de pessoal" },
    { code: "025", desc: "Operações e rotinas de bibliotecas e documentação" },
    { code: "025.1", desc: "Administração de bibliotecas" },
    { code: "025.2", desc: "Aquisição e desenvolvimento da coleção" },
    { code: "025.3", desc: "Análise bibliográfica e controle (Catalogação)" },
    { code: "025.4", desc: "Análises de assuntos e controle (CDD, CDU)" },
    { code: "025.5", desc: "Serviços aos usuários (Referência)" },
    { code: "030", desc: "Enciclopédias gerais" },
    { code: "050", desc: "Publicações seriadas e revistas" },
    { code: "060", desc: "Organizações gerais e museologia" },
    { code: "070", desc: "Notícias da mídia, jornalismo e editorial" },
    { code: "071", desc: "Jornais na América do Norte" },
    { code: "072", desc: "Jornais nas ilhas britânicas; na Inglaterra" },
    { code: "073", desc: "Jornais na Europa central; na Alemanha" },
    { code: "074", desc: "Jornais na França e Mônaco" },
    { code: "075", desc: "Jornais na Itália e ilhas adjacentes" },
    { code: "076", desc: "Jornais na Península Ibérica e ilhas adjacentes" },
    { code: "077", desc: "Jornais na Europa oriental; na Rússia" },
    { code: "078", desc: "Jornais na Escandinávia" },
    { code: "079", desc: "Jornais em outras áreas geográficas" },
    { code: "080", desc: "Coleções gerais" },
    { code: "090", desc: "Manuscritos e livros raros" },
    { code: "100", desc: "Filosofia e psicologia" },
    { code: "110", desc: "Metafísica" },
    { code: "120", desc: "Epistemologia, causalidade, gênero humano" },
    { code: "130", desc: "Parapsicologia e ocultismo" },
    { code: "133", desc: "Tópicos específicos em parapsicologia e ocultismo" },
    { code: "140", desc: "Escolas filosóficas específicas" },
    { code: "150", desc: "Psicologia" },
    { code: "152", desc: "Percepção, movimento, emoções" },
    { code: "153", desc: "Processos mentais e inteligência" },
    { code: "154", desc: "Subconsciente e estados alterados" },
    { code: "155", desc: "Psicologia diferencial e do desenvolvimento" },
    { code: "158", desc: "Psicologia aplicada (Autoajuda)" },
    { code: "158.1", desc: "Comportamento, Auto ajuda, Aperfeiçoamento pessoal" },
    { code: "158.125", desc: "Meditação transcendental" },
    { code: "158.128", desc: "Meditação" },
    { code: "160", desc: "Lógica" },
    { code: "170", desc: "Ética (Filosofia moral)" },
    { code: "180", desc: "Filosofia antiga, medieval e oriental" },
    { code: "190", desc: "Filosofia ocidental moderna" },
    { code: "200", desc: "Religião" },
    { code: "210", desc: "Filosofia e teoria da religião" },
    { code: "220", desc: "Bíblia" },
    { code: "221", desc: "Antigo Testamento" },
    { code: "225", desc: "Novo Testamento" },
    { code: "230", desc: "Cristianismo e teologia cristã" },
    { code: "240", desc: "Moral cristã e teologia devocional" },
    { code: "250", desc: "Ordens cristãs e igreja local" },
    { code: "260", desc: "Teologia social e eclesiologia" },
    { code: "270", desc: "História do cristianismo" },
    { code: "280", desc: "Denominações e seitas cristãs" },
    { code: "290", desc: "Outras religiões" },
    { code: "294", desc: "Religiões de origem indiana (Budismo, Hinduísmo)" },
    { code: "296", desc: "Judaísmo" },
    { code: "297", desc: "Islamisno" },
    { code: "300", desc: "Ciências sociais" },
    { code: "301", desc: "Sociologia e antropologia" },
    { code: "302", desc: "Interação social" },
    { code: "303", desc: "Processos sociais (Guerra, Conflito)" },
    { code: "304", desc: "Fatores que afetam o comportamento social" },
    { code: "305", desc: "Grupos sociais (Jovens, Idosos, Mulheres)" },
    { code: "306", desc: "Cultura e instituições" },
    { code: "310", desc: "Coleções de estatística geral" },
    { code: "314", desc: "Estatística geral da Europa" },
    { code: "315", desc: "Estatística geral da Ásia" },
    { code: "316", desc: "Estatística geral da África" },
    { code: "317", desc: "Estatística geral da América do Norte" },
    { code: "318", desc: "Estatística geral da América do Sul" },
    { code: "319", desc: "Estatística geral de outras áreas" },
    { code: "320", desc: "Ciência política" },
    { code: "327", desc: "Relações internacionais" },
    { code: "330", desc: "Economia" },
    { code: "331", desc: "Economia trabalhista" },
    { code: "332", desc: "Economia financeira" },
    { code: "333", desc: "Economia de terra e energia" },
    { code: "334", desc: "Cooperativas" },
    { code: "335", desc: "Socialismo e sistemas relacionados" },
    { code: "336", desc: "Finanças públicas" },
    { code: "337", desc: "Economia internacional" },
    { code: "338", desc: "Produção" },
    { code: "339", desc: "Macroeconomia e tópicos relacionados" },
    { code: "340", desc: "Direito" },
    { code: "341", desc: "Direito das nações" },
    { code: "342", desc: "Direito constitucional e administrativo" },
    { code: "343", desc: "Direito militar, impostos, mercantil e industrial" },
    { code: "344", desc: "Direito trabalhista, social, educacional e cultural" },
    { code: "345", desc: "Direito criminal" },
    { code: "346", desc: "Direito privado" },
    { code: "347", desc: "Procedimento e tribunais cíveis" },
    { code: "348", desc: "Leis, regulamentos e casos" },
    { code: "349", desc: "Direiro de específicas jurisdições e áreas" },
    { code: "350", desc: "Administração pública e ciência militar" },
    { code: "360", desc: "Problemas e serviços sociais" },
    { code: "362", desc: "Serviços de bem-estar social" },
    { code: "364", desc: "Criminologia" },
    { code: "370", desc: "Educação" },
    { code: "371", desc: "Escolas e suas atividades; educação especial" },
    { code: "372", desc: "Ensino Fundamental" },
    { code: "373", desc: "Ensino Secundário" },
    { code: "374", desc: "Ensino adulto" },
    { code: "375", desc: "Currículos" },
    { code: "378", desc: "Ensino Superior" },
    { code: "379", desc: "Assuntos de politica pública na educação" },
    { code: "380", desc: "Comércio, comunicações e transporte" },
    { code: "390", desc: "Costumes, etiqueta e folclore" },
    { code: "400", desc: "Linguagem" },
    { code: "410", desc: "Linguística" },
    { code: "419", desc: "Linguagem de sinais" },
    { code: "420", desc: "Inglês e inglês antigo" },
    { code: "430", desc: "Línguas germânicas (Alemão)" },
    { code: "440", desc: "Línguas românicas (Francês)" },
    { code: "450", desc: "Italiano, romeno" },
    { code: "460", desc: "Espanhol e Português" },
    { code: "469", desc: "Português" },
    { code: "470", desc: "Línguas itálicas (Latim)" },
    { code: "480", desc: "Línguas helênicas (Grego)" },
    { code: "490", desc: "Outras línguas" },
    { code: "500", desc: "Ciências naturais e matemática" },
    { code: "510", desc: "Matemática" },
    { code: "511", desc: "Princípios gerais da matemática" },
    { code: "512", desc: "Álgebra" },
    { code: "513", desc: "Aritmética" },
    { code: "514", desc: "Topologia" },
    { code: "515", desc: "Análise e cálculo" },
    { code: "516", desc: "Geometria" },
    { code: "519", desc: "Probabilidades e matemática aplicada" },
    { code: "520", desc: "Astronomia" },
    { code: "523", desc: "Corpos celestes específicos" },
    { code: "530", desc: "Física" },
    { code: "531", desc: "Mecânica clássica" },
    { code: "535", desc: "Luz e ótica" },
    { code: "537", desc: "Eletricidade e eletrônica" },
    { code: "539", desc: "Física moderna" },
    { code: "540", desc: "Química" },
    { code: "550", desc: "Ciências da Terra e Geologia" },
    { code: "560", desc: "Paleontologia (Fósseis)" },
    { code: "570", desc: "Ciências da vida e Biologia" },
    { code: "572", desc: "Bioquímica" },
    { code: "576", desc: "Genética e evolução" },
    { code: "577", desc: "Ecologia" },
    { code: "580", desc: "Plantas (Botânica)" },
    { code: "590", desc: "Animais (Zoologia)" },
    { code: "595", desc: "Artrópodes (Insetos, Aranhas)" },
    { code: "597", desc: "Vertebrados de sangue frio (Peixes, Répteis)" },
    { code: "598", desc: "Aves" },
    { code: "599", desc: "Mamíferos" },
    { code: "600", desc: "Tecnologia" },
    { code: "610", desc: "Medicina e saúde" },
    { code: "611", desc: "Anatomia humana" },
    { code: "612", desc: "Fisiologia humana" },
    { code: "613", desc: "Promoção da saúde (Higiene, Fitness)" },
    { code: "615", desc: "Farmacologia e terapêutica" },
    { code: "616", desc: "Doenças" },
    { code: "617", desc: "Cirurgia" },
    { code: "618", desc: "Ginecologia, obstetrícia, pediatria" },
    { code: "620", desc: "Engenharia e operações afins" },
    { code: "621", desc: "Física aplicada (Elétrica, Eletrônica, Mecânica)" },
    { code: "624", desc: "Engenharia civil" },
    { code: "629", desc: "Outros ramos da engenharia (Automóveis, Aeroespacial)" },
    { code: "630", desc: "Agricultura" },
    { code: "636", desc: "Pecuária e animais de estimação" },
    { code: "640", desc: "Gestão doméstica e familiar" },
    { code: "641", desc: "Comida e bebida (Culinária)" },
    { code: "650", desc: "Gestão e serviços auxiliares" },
    { code: "657", desc: "Contabilidade" },
    { code: "658", desc: "Gestão geral (Administração)" },
    { code: "659", desc: "Publicidade e relações públicas" },
    { code: "660", desc: "Engenharia química" },
    { code: "670", desc: "Fabricação industrial" },
    { code: "680", desc: "Fabricação de produtos para usos específicos" },
    { code: "690", desc: "Construção de edifícios" },
    { code: "700", desc: "Artes" },
    { code: "709", desc: "História da arte" },
    { code: "710", desc: "Urbanismo e paisagismo" },
    { code: "720", desc: "Arquitetura" },
    { code: "730", desc: "Artes plásticas e escultura" },
    { code: "740", desc: "Desenho e artes decorativas" },
    { code: "741", desc: "Desenho e caricaturas (Quadrinhos)" },
    { code: "745", desc: "Artes decorativas" },
    { code: "750", desc: "Pintura" },
    { code: "760", desc: "Artes gráficas e gravuras" },
    { code: "770", desc: "Fotografia" },
    { code: "780", desc: "Música" },
    { code: "781", desc: "Teoria musical e formas gerais" },
    { code: "782", desc: "Música vocal" },
    { code: "784", desc: "Instrumentos e conjuntos" },
    { code: "786", desc: "Instrumentos de teclado" },
    { code: "787", desc: "Instrumentos de corda" },
    { code: "790", desc: "Artes recreativas e de espetáculo" },
    { code: "791", desc: "Espetáculos públicos (Cinema, Circo)" },
    { code: "792", desc: "Teatro" },
    { code: "793", desc: "Jogos e diversões de salão" },
    { code: "794", desc: "Jogos de habilidade (Xadrez, Computador)" },
    { code: "796", desc: "Esportes e jogos atléticos" },
    { code: "800", desc: "Literatura e retórica" },
    { code: "810", desc: "Literatura americana em inglês" },
    { code: "820", desc: "Literatura inglesa" },
    { code: "830", desc: "Literatura alemã" },
    { code: "840", desc: "Literatura francesa" },
    { code: "850", desc: "Literatura italiana" },
    { code: "860", desc: "Literaturas espanhola e portuguesa" },
    { code: "869", desc: "Literatura brasileira e portuguesa" },
    { code: "869.1", desc: "Poesia brasileira" },
    { code: "869.2", desc: "Teatro brasileiro" },
    { code: "869.3", desc: "Romance e ficção brasileira" },
    { code: "869.4", desc: "Ensaios brasileiros" },
    { code: "869.9", desc: "Literatura portuguesa" },
    { code: "870", desc: "Literaturas itálicas (Latina)" },
    { code: "880", desc: "Literaturas helênicas (Grega clássica)" },
    { code: "890", desc: "Literaturas de outras línguas" },
    { code: "900", desc: "História e geografia" },
    { code: "901", desc: "Filosofia e teoria da história" },
    { code: "902", desc: "Miscelânea histórica" },
    { code: "903", desc: "Dicionários e enciclopédias históricas" },
    { code: "904", desc: "Relatos coletivos de eventos" },
    { code: "905", desc: "Publicações em série históricas" },
    { code: "906", desc: "Organizações e gerenciamento" },
    { code: "907", desc: "Educação, pesquisa e tópicos relacionados" },
    { code: "908", desc: "Tratamento da história por classe de pessoas" },
    { code: "909", desc: "História do mundo (Geral)" },
    { code: "910", desc: "Geografia e viagens" },
    { code: "914", desc: "Geografia da Europa" },
    { code: "918", desc: "Geografia da América do Sul" },
    { code: "920", desc: "Biografia, genealogia, insígnias" },
    { code: "928", desc: "Biografias de escritores e personagens históricos" },
    { code: "928.1", desc: "Escritores americanos" },
    { code: "928.69", desc: "Escritores portugueses" },
    { code: "928.6981", desc: "Escritores brasileiros" },
    { code: "929", desc: "Genealogia, nomes e insígnia" },
    { code: "930", desc: "História do mundo antigo (até ca. 499 d.C.)" },
    { code: "931", desc: "China antiga (até 420)" },
    { code: "932", desc: "Egito antigo (até 640)" },
    { code: "933", desc: "Palestina (até 70)" },
    { code: "934", desc: "Índia antiga (até 647)" },
    { code: "935", desc: "Mesopotâmia e planalto iraniano (até 637)" },
    { code: "936", desc: "Norte da Europa e oeste da Itália (até ca. 499)" },
    { code: "937", desc: "Itália antiga e territórios adjacentes (até 476)" },
    { code: "938", desc: "Grécia antiga (até 323)" },
    { code: "939", desc: "Outras partes do mundo antigo (até 640)" },
    { code: "940", desc: "História da Europa" },
    { code: "941", desc: "Ilhas britânicas" },
    { code: "942", desc: "Inglaterra e Gales" },
    { code: "943", desc: "Europa central; Alemanha" },
    { code: "944", desc: "França e Mônaco" },
    { code: "945", desc: "Península itálica e ilhas adjacentes" },
    { code: "946", desc: "Península ibérica e ilhas adjacentes" },
    { code: "947", desc: "Europa oriental; Rússia" },
    { code: "948", desc: "Escandinávia" },
    { code: "949", desc: "Outras partes da Europa" },
    { code: "950", desc: "História da Ásia; Oriente distante" },
    { code: "951", desc: "China e áreas adjacentes" },
    { code: "952", desc: "Japão" },
    { code: "953", desc: "Península árabe e áreas adjacentes" },
    { code: "954", desc: "Sul da Ásia; Índia" },
    { code: "955", desc: "Irã" },
    { code: "956", desc: "Oriente Médio (Oriente próximo)" },
    { code: "957", desc: "Sibéria (Rússia asiática)" },
    { code: "958", desc: "Ásia central" },
    { code: "959", desc: "Sudeste da Ásia" },
    { code: "960", desc: "História da África" },
    { code: "961", desc: "Tunísia e Líbia" },
    { code: "962", desc: "Egito e Sudão" },
    { code: "963", desc: "Etiópia e Eritréia" },
    { code: "964", desc: "Costa do noroeste da África e ilhas litorâneas" },
    { code: "965", desc: "Algéria" },
    { code: "966", desc: "Oeste da África e ilhas litorâneas" },
    { code: "967", desc: "África central e ilhas litorâneas" },
    { code: "968", desc: "África do Sul; República da África do Sul" },
    { code: "969", desc: "Ilhas do oceano Índico-sul" },
    { code: "970", desc: "História da América do Norte" },
    { code: "971", desc: "Canadá" },
    { code: "972", desc: "Mesoamérica; México" },
    { code: "973", desc: "Estados Unidos" },
    { code: "974", desc: "Nordeste dos Estados Unidos" },
    { code: "975", desc: "Sudeste dos Estados Unidos" },
    { code: "976", desc: "Centro-sul dos Estados Unidos" },
    { code: "977", desc: "Centro-norte dos Estados Unidos" },
    { code: "978", desc: "Oeste dos Estados Unidos" },
    { code: "979", desc: "Região da Grande Bacia e Vertente do Pacífico" },
    { code: "980", desc: "História da América do Sul" },
    { code: "981", desc: "História do Brasil" },
    { code: "981.01", desc: "Brasil Colônia" },
    { code: "981.03", desc: "Brasil Império" },
    { code: "981.06", desc: "Brasil República" },
    { code: "982", desc: "Argentina" },
    { code: "983", desc: "Chile" },
    { code: "984", desc: "Bolívia" },
    { code: "985", desc: "Perú" },
    { code: "986", desc: "Colômbia e Equador" },
    { code: "987", desc: "Venezuela" },
    { code: "988", desc: "Guiana" },
    { code: "989", desc: "Paraguai e Uruguai" },
    { code: "990", desc: "História de outras áreas" },
    { code: "993", desc: "Nova Zelândia" },
    { code: "994", desc: "Austrália" },
    { code: "995", desc: "Melanésia; Nova Guiné" },
    { code: "996", desc: "Outras partes do Pacífico; Polinésia" },
    { code: "997", desc: "Ilhas do oceano Atlântico" },
    { code: "998", desc: "Ilhas do Ártico e Antártica" },
    { code: "999", desc: "Mundos extraterrestres" }
];

/* --- BASE CDU (Universal) --- */
const baseCDU = [
    { code: "0", desc: "Ciência e conhecimento. Organização. Informática. Informação. Documentação. Biblioteconomia. Instituições. Publicações" },
    { code: "00", desc: "Prolegómenos. Fundamentos do conhecimento e da cultura. Propadéutica" },
    { code: "001", desc: "Ciência e conhecimento em geral. Organização do trabalho intelectual" },
    { code: "001.1", desc: "Conceitos da ciência e do conhecimento" },
    { code: "001.18", desc: "Futuro do conhecimento" },
    { code: "001.32", desc: "Sociedades eruditas, científicas. Academias" },
    { code: "001.8", desc: "Metodologia" },
    { code: "001.89", desc: "Organização da ciência e do trabalho científico" },
    { code: "001.9", desc: "Disseminação das ideias" },
    { code: "002", desc: "Documentação. Livros. Escritos. Autoria" },
    { code: "003", desc: "Sistemas de escrita e escritas" },
    { code: "003.01", desc: "Origens, precursores da escrita. Formas primitivas de escrita" },
    { code: "003.02", desc: "Aparecimento da escrita" },
    { code: "003.03", desc: "Expressão gráfica da linguagem" },
    { code: "003.05", desc: "Meios de produção de signos e escritas" },
    { code: "003.07", desc: "Usos e estilos da escrita" },
    { code: "003.08", desc: "Características da escrita" },
    { code: "003.09", desc: "Técnicas e métodos de decifração de escritas" },
    { code: "003.2", desc: "Sistemas de escrita. Representação gráfica de conceitos" },
    { code: "003.21", desc: "Escrita pictográfica" },
    { code: "003.22", desc: "Sistemas de escrita silábicos" },
    { code: "003.23", desc: "Sistemas de escrita alfabéticos" },
    { code: "003.3", desc: "Escritas" },
    { code: "003.5", desc: "Materiais e equipamentos de escrita" },
    { code: "003.6", desc: "Outros tipos de representação gráfica do pensamento" },
    { code: "004", desc: "Ciência e tecnologia informáticas. Computação. Processamento de dados" },
    { code: "004.01", desc: "Documentação" },
    { code: "004.02", desc: "Métodos de resolução dos problemas" },
    { code: "004.03", desc: "Tipos e características dos sistemas" },
    { code: "004.04", desc: "Orientação do processamento" },
    { code: "004.05", desc: "Qualidade dos sistemas e do software" },
    { code: "004.07", desc: "Características da memória" },
    { code: "004.08", desc: "Dispositivos de entrada (input), saída (output) e armazenamento" },
    { code: "004.2", desc: "Arquitectura dos computadores" },
    { code: "004.22", desc: "Representação dos dados" },
    { code: "004.23", desc: "Arquitectura de conjunto de instruções" },
    { code: "004.25", desc: "Sistemas de memória" },
    { code: "004.27", desc: "Arquitecturas avançadas. Outras arquitecturas que a de Von Neumann" },
    { code: "004.3", desc: "Equipamento informático. Hardware" },
    { code: "004.31", desc: "Unidades de processamento. Circuitos de processamento" },
    { code: "004.32", desc: "Circuitos do computador" },
    { code: "004.33", desc: "Unidades da memória. Unidades de armazenamento" },
    { code: "004.35", desc: "Periféricos. Unidades de entrada e saída (input-output)" },
    { code: "004.38", desc: "Computador. Tipos de computador" },
    { code: "004.4", desc: "Programas de computador (software)" },
    { code: "004.41", desc: "Engenharia de software" },
    { code: "004.42", desc: "Programação de computadores. Programas de computador" },
    { code: "004.43", desc: "Linguagens de computador" },
    { code: "004.45", desc: "Programas de sistemas" },
    { code: "004.49", desc: "Infecções de computador" },
    { code: "004.5", desc: "Interacção homem-computador. Interface homem-máquina. Interface do utilizador" },
    { code: "004.51", desc: "Interface de exibição" },
    { code: "004.52", desc: "Interface de som" },
    { code: "004.55", desc: "Hipermédia. Hipertexto" },
    { code: "004.58", desc: "Ajuda ao utilizador" },
    { code: "004.6", desc: "Dados" },
    { code: "004.62", desc: "Tratamento de dados" },
    { code: "004.63", desc: "Ficheiros" },
    { code: "004.65", desc: "Bases de dados e suas estruturas" },
    { code: "004.67", desc: "Sistemas para dados numéricos" },
    { code: "004.7", desc: "Comunicação de computadores. Redes de computadores" },
    { code: "004.71", desc: "Equipamento para comunicação entre computadores" },
    { code: "004.72", desc: "Arquitectura de redes" },
    { code: "004.73", desc: "Redes de acordo com a área coberta" },
    { code: "004.738", desc: "Interconexão de redes" },
    { code: "004.75", desc: "Sistemas de processamento distribuído" },
    { code: "004.77", desc: "Aplicações e serviços gerais de rede" },
    { code: "004.78", desc: "Sistemas de computadores em linha para fins específicos" },
    { code: "004.8", desc: "Inteligência artificial" },
    { code: "004.9", desc: "Técnicas baseadas em computadores e orientadas para aplicações" },
    { code: "004.91", desc: "Processamento e produção do documento" },
    { code: "004.92", desc: "Infografia. Computação gráfica" },
    { code: "004.93", desc: "Processamento de padrões de informação" },
    { code: "004.94", desc: "Simulação" },
    { code: "005", desc: "Gestão" },
    { code: "005.1", desc: "Teoria da gestão" },
    { code: "005.2", desc: "Agentes da gestão. Mecanismos. Medidas" },
    { code: "005.3", desc: "Actividades de gestão" },
    { code: "005.31", desc: "Investigação operacional (IO)" },
    { code: "005.32", desc: "Comportamento organizacional. Psicologia da gestão" },
    { code: "005.33", desc: "Factores condicionantes da gestão" },
    { code: "005.4", desc: "Processos na gestão" },
    { code: "005.5", desc: "Operações de gestão. Direcção" },
    { code: "005.6", desc: "Gestão da qualidade. Gestão da qualidade total (TQM)" },
    { code: "005.7", desc: "Gestão da organização" },
    { code: "005.9", desc: "Áreas, campos da gestão" },
    { code: "005.91", desc: "Gestão administrativa. Secretariado" },
    { code: "005.92", desc: "Gestão de documentos de arquivo (gestão de registos)" },
    { code: "005.93", desc: "Gestão das instalações. Gestão dos recursos físicos" },
    { code: "005.94", desc: "Gestão de conhecimentos" },
    { code: "005.95", desc: "Gestão de pessoal. Gestão de recursos humanos" },
    { code: "006", desc: "Normalização de produtos, operações, pesos, medidas e tempo" },
    { code: "006.91", desc: "Metrologia. Pesos e medidas em geral" },
    { code: "006.92", desc: "Horologia. Determinação e normalização do tempo" },
    { code: "007", desc: "Actividade e organização. Teoria da comunicação e do controlo (cibernética)" },
    { code: "007.5", desc: "Sistemas automáticos" },
    { code: "008", desc: "Civilização. Cultura. Progresso" },
    { code: "01", desc: "Bibliografia e bibliografias. Catálogos" },
    { code: "011", desc: "Bibliografias universais e gerais" },
    { code: "012", desc: "Bibliografias de autores. Bibliografias individuais" },
    { code: "013", desc: "Bibliografias colectivas" },
    { code: "014", desc: "Bibliografias de obras com características especiais" },
    { code: "015", desc: "Bibliografias segundo o lugar" },
    { code: "016", desc: "Bibliografias de assuntos específicos. Bibliografias especializadas" },
    { code: "017", desc: "Catálogos em geral. Catálogos de assunto" },
    { code: "018", desc: "Catálogos onomásticos" },
    { code: "019", desc: "Catálogos-dicionários" },
    { code: "02", desc: "Biblioteconomia" },
    { code: "021", desc: "Função, valor, utilidade, criação, desenvolvimento de bibliotecas" },
    { code: "022", desc: "Localização da biblioteca, edifícios. Equipamento" },
    { code: "023", desc: "Administração da biblioteca. Pessoal" },
    { code: "024", desc: "Relações da biblioteca com o público. Regulamentos sobre o uso da biblioteca" },
    { code: "025", desc: "Departamentos administrativos das bibliotecas" },
    { code: "026", desc: "Bibliotecas especializadas" },
    { code: "027", desc: "Bibliotecas gerais" },
    { code: "027.6", desc: "Bibliotecas destinadas a determinadas categorias de leitores" },
    { code: "027.7", desc: "Bibliotecas de estabelecimentos de ensino superior" },
    { code: "027.8", desc: "Bibliotecas de estabelecimentos de ensino primário e secundário" },
    { code: "030", desc: "Obras gerais de referência (como assunto)" },
    { code: "050", desc: "Publicações periódicas, periódicos (como assunto)" },
    { code: "06", desc: "Organizações em geral" },
    { code: "06.01", desc: "Direitos e deveres dos membros" },
    { code: "06.05", desc: "Recompensas. Distinções. Prémios" },
    { code: "061", desc: "Organizações e outros tipos de cooperação" },
    { code: "061.1", desc: "Organizações e cooperação governamentais" },
    { code: "061.2", desc: "Organizações e cooperação não governamentais" },
    { code: "061.23", desc: "Organizações com fins humanitários, filantrópicos" },
    { code: "061.25", desc: "Organizações e movimentos secretos e semi-secretos" },
    { code: "061.27", desc: "Fundações. Dotações. Institutos" },
    { code: "069", desc: "Museus. Exposições permanentes" },
    { code: "070", desc: "Jornais. Imprensa" },
    { code: "08", desc: "Poligrafias. Obras de autoria colectiva" },
    { code: "082", desc: "Poligrafias colectivas" },
    { code: "084", desc: "Material pictórico" },
    { code: "086", desc: "Documentos de forma particular" },
    { code: "087", desc: "Documentos de origem ou destino particular" },
    { code: "09", desc: "Manuscritos. Obras raras e notáveis" },
    { code: "091", desc: "Manuscritos" },
    { code: "092", desc: "Livros xilográficos" },
    { code: "093", desc: "Incunábulos" },
    { code: "094", desc: "Outras obras impressas notáveis e raras" },
    { code: "095", desc: "Obras notáveis pela encadernação" },
    { code: "096", desc: "Obras notáveis pelas ilustrações ou pelos materiais utilizados" },
    { code: "097", desc: "Marcas de propriedade ou de origem" },
    { code: "1", desc: "Filosofia. Psicologia" },
    { code: "101", desc: "Natureza e âmbito da filosofia" },
    { code: "11", desc: "Metafísica" },
    { code: "111", desc: "Metafísica geral. Ontologia" },
    { code: "13", desc: "Filosofia da mente e do espírito. Metafísica da vida espiritual" },
    { code: "130.1", desc: "Conceitos e leis gerais" },
    { code: "130.2", desc: "Filosofia da cultura. Sistemas culturais" },
    { code: "130.3", desc: "Metafísica da vida espiritual" },
    { code: "133", desc: "Paranormal. O oculto. Fenómenos psi" },
    { code: "14", desc: "Sistemas e pontos de vista filosóficos" },
    { code: "140", desc: "Atitudes filosóficas possíveis. Tipologia de sistemas filosóficos" },
    { code: "141", desc: "Tipos de pontos de vista filosóficos" },
    { code: "159.9", desc: "Psicologia" },
    { code: "159.91", desc: "Psicofisiologia (psicologia fisiológica). Fisiologia mental" },
    { code: "159.92", desc: "Desenvolvimento e capacidade mental. Psicologia comparada" },
    { code: "159.93", desc: "Sensação. Percepção sensorial" },
    { code: "159.94", desc: "Funções executivas" },
    { code: "159.942", desc: "Emoções. Afectos. Sensibilidade. Sentimentos" },
    { code: "159.943", desc: "Conação e movimento" },
    { code: "159.944", desc: "Trabalho e fadiga. Eficiência" },
    { code: "159.946", desc: "Funções motoras especiais" },
    { code: "159.947", desc: "Volição. Vontade" },
    { code: "159.95", desc: "Processos mentais superiores" },
    { code: "159.96", desc: "Estados e processos mentais especiais" },
    { code: "159.97", desc: "Psicopatologia" },
    { code: "159.98", desc: "Psicologia aplicada (psicotecnologia) em geral" },
    { code: "16", desc: "Lógica. Epistemologia. Teoria do conhecimento" },
    { code: "161", desc: "Fundamentos da lógica" },
    { code: "164", desc: "Logística. Lógica simbólica. Lógica matemática" },
    { code: "165", desc: "Teoria do conhecimento. Epistemologia" },
    { code: "17", desc: "Filosofia moral. Ética. Filosofia prática" },
    { code: "171", desc: "Ética individual. Deveres do indivíduo para consigo mesmo" },
    { code: "172", desc: "Ética social. Deveres para com os outros" },
    { code: "173", desc: "Ética familiar" },
    { code: "176", desc: "Ética sexual. Moralidade sexual" },
    { code: "177", desc: "Ética e sociedade" },
    { code: "2", desc: "Religião. Teologia" },
    { code: "2-1", desc: "Teoria e filosofia da religião. Natureza da religião" },
    { code: "2-13", desc: "O divino. O Sagrado. O Sobrenatural" },
    { code: "2-14", desc: "Deus. Deuses" },
    { code: "2-15", desc: "Natureza de Deus(es)" },
    { code: "2-17", desc: "Universo. Natureza do Universo. Cosmologia" },
    { code: "2-18", desc: "Homem. Humanidade. Condição humana" },
    { code: "2-184", desc: "Relação do Homem com Deus(es)" },
    { code: "2-2", desc: "Provas da religião" },
    { code: "2-23", desc: "Livros sagrados. Escrituras. Textos religiosos" },
    { code: "2-25", desc: "Literatura secundária. Obras pseudocanónicas" },
    { code: "2-27", desc: "Obras críticas" },
    { code: "2-28", desc: "Outros textos religiosos" },
    { code: "2-3", desc: "Pessoas na religião" },
    { code: "2-31", desc: "Criador, fundador, figura central da fé" },
    { code: "2-32", desc: "Messias" },
    { code: "2-34", desc: "Mártires" },
    { code: "2-35", desc: "Ascetas. Eremitas. Faquires" },
    { code: "2-36", desc: "Santos. Bodhisattvas. Pessoas iluminadas" },
    { code: "2-37", desc: "Mahatmas. Gurus. Sábios" },
    { code: "2-38", desc: "Carismáticos. Pessoas com poderes sobrenaturais" },
    { code: "2-4", desc: "Actividades religiosas. Práticas religiosas" },
    { code: "2-42", desc: "Comportamento moral. Teologia moral" },
    { code: "2-43", desc: "Costumes e prática social. Teologia social" },
    { code: "2-46", desc: "Caridade. Apoio aos outros. Actividades pastorais" },
    { code: "2-47", desc: "Educação religiosa" },
    { code: "2-475", desc: "Pregação. Homiliética" },
    { code: "2-5", desc: "Veneração. Culto. Rituais e cerimónias" },
    { code: "2-523", desc: "Edifícios para uso religioso. Eclesiologia" },
    { code: "2-526", desc: "Objectos do culto. Mobiliário e decoração" },
    { code: "2-53", desc: "Actos de veneração/adoração" },
    { code: "2-54", desc: "Cerimónias segundo o objectivo" },
    { code: "2-55", desc: "Sacramentos" },
    { code: "2-56", desc: "Celebração" },
    { code: "2-6", desc: "Processos em religião" },
    { code: "2-65", desc: "Comparação de religiões" },
    { code: "2-67", desc: "Relações entre confissões religiosas" },
    { code: "2-7", desc: "Organização e administração religiosa" },
    { code: "2-72", desc: "Natureza e estructura da religião organizada" },
    { code: "2-73", desc: "Governo da religião" },
    { code: "2-74", desc: "Administração legal. Lei religiosa. Direito canónico" },
    { code: "2-76", desc: "Recrutamento. Actividade missionária" },
    { code: "2-77", desc: "Estrutura organizacional da fé, da religião" },
    { code: "2-78", desc: "Organizações religiosas. Sociedades e associações religiosas" },
    { code: "2-84", desc: "Religiões associadas ao Estado" },
    { code: "2-87", desc: "Cismas. Heresias" },
    { code: "2-9", desc: "História da fé, religião, denominação ou igreja" },
    { code: "21", desc: "Religiões pré-históricas e primitivas" },
    { code: "212", desc: "Religiões pré-históricas" },
    { code: "213", desc: "Religiões primitivas" },
    { code: "22", desc: "Religiões originárias do Extremo Oriente" },
    { code: "221", desc: "Religiões da China" },
    { code: "221.3", desc: "Taoismo" },
    { code: "223", desc: "Religiões da Coreia" },
    { code: "225", desc: "Religiões do Japão" },
    { code: "23", desc: "Religiões originárias do sub-continente indiano. Hinduísmo" },
    { code: "233", desc: "Hinduismo em sentido restrito" },
    { code: "234", desc: "Jainismo" },
    { code: "235", desc: "Sikhismo" },
    { code: "24", desc: "Budismo" },
    { code: "241", desc: "Budismo hinayana. O Pequeno Veículo" },
    { code: "242", desc: "Budismo mahayana. O Grande Veículo" },
    { code: "243", desc: "Lamaísmo" },
    { code: "244", desc: "Budismo japonês" },
    { code: "25", desc: "Religiões da antiguidade. Cultos e religiões menores" },
    { code: "251", desc: "Religião do Egipto antigo" },
    { code: "252", desc: "Religiões da Mesopotâmia" },
    { code: "254", desc: "Religiões do Irão" },
    { code: "255", desc: "Religiões da antiguidade clássica" },
    { code: "257", desc: "Religiões da Europa" },
    { code: "258", desc: "Religiões da América Central e do Sul" },
    { code: "26", desc: "Judaísmo" },
    { code: "261", desc: "Religião do período Bíblico. Judaísmo antigo" },
    { code: "262", desc: "Judaísmo asquenazita" },
    { code: "264", desc: "Judaísmo sefardita" },
    { code: "265", desc: "Judaísmo ortodoxo" },
    { code: "266", desc: "Judaísmo progressista" },
    { code: "267", desc: "Movimentos modernos originários do Judaísmo" },
    { code: "27", desc: "Cristianismo. Igrejas e denominações cristãs" },
    { code: "271", desc: "Igrejas do Oriente" },
    { code: "272", desc: "Igreja Católica Romana" },
    { code: "273", desc: "Igrejas episcopais católicas não filiadas a Roma" },
    { code: "274", desc: "Protestantismo em sentido lato" },
    { code: "275", desc: "Igrejas reformadas" },
    { code: "276", desc: "Anabaptistas" },
    { code: "277", desc: "Igrejas livres. Não conformistas" },
    { code: "278", desc: "Outras igrejas protestantes" },
    { code: "279", desc: "Outros movimentos e igrejas cristãs" },
    { code: "28", desc: "Islamismo" },
    { code: "281", desc: "Sufismo" },
    { code: "282", desc: "Sunni. Islamismo sunita" },
    { code: "284", desc: "Shi'a. Islamismo xiita" },
    { code: "285", desc: "Babismo" },
    { code: "286", desc: "Bahaísmo" },
    { code: "29", desc: "Movimentos espirituais modernos" },
    { code: "3", desc: "Ciências Sociais" },
    { code: "303", desc: "Métodos das ciências sociais" },
    { code: "304", desc: "Questões sociais. Prática social" },
    { code: "305", desc: "Estudos do género" },
    { code: "308", desc: "Sociografia" },
    { code: "311", desc: "Estatística como ciência. Teoria estatística" },
    { code: "311.1", desc: "Fundamentos, bases da estatística" },
    { code: "311.2", desc: "Técnica de pesquisa. Preparação. Tabulação" },
    { code: "311.3", desc: "Organização geral das estatísticas. Estatísticas oficiais" },
    { code: "311.4", desc: "Estatísticas privadas" },
    { code: "314", desc: "Demografia. Estudos da população" },
    { code: "314.1", desc: "População" },
    { code: "316", desc: "Sociologia" },
    { code: "316.1", desc: "Objecto e âmbito da sociologia" },
    { code: "316.2", desc: "Pontos de vista e tendências sociológicas" },
    { code: "316.3", desc: "Estrutura social. Sociedade como sistema social" },
    { code: "316.33", desc: "Elementos básicos e subsistemas das sociedades globais" },
    { code: "316.34", desc: "Estratificação social. Diferenciação social" },
    { code: "316.35", desc: "Grupos sociais. Organizações sociais" },
    { code: "316.36", desc: "Casamento e familía" },
    { code: "316.4", desc: "Processos sociais. Dinâmicas sociais" },
    { code: "316.6", desc: "Psicologia social" },
    { code: "316.7", desc: "Sociologia da cultura. Contexto cultural da vida social" },
    { code: "32", desc: "Política" },
    { code: "321", desc: "Formas de organização política. Estados como poderes políticos" },
    { code: "322", desc: "Relações entre o estado e a igreja" },
    { code: "323", desc: "Assuntos internos. Política interna" },
    { code: "323.1", desc: "Movimentos e problemas nacionalistas, populares e étnicos" },
    { code: "323.2", desc: "Relações entre a população e o Estado" },
    { code: "323.4", desc: "Luta de classes" },
    { code: "324", desc: "Eleições. Plebiscitos. Referendos" },
    { code: "325", desc: "Abertura de territórios. Colonização. Colonialismo" },
    { code: "326", desc: "Escravatura" },
    { code: "327", desc: "Relações internacionais. Política mundial" },
    { code: "327.2", desc: "Imperialismo. Política imperialista" },
    { code: "327.3", desc: "Internacionalismo" },
    { code: "327.5", desc: "Blocos internacionais" },
    { code: "327.7", desc: "Actividade das organizações internacionais e intergovernamentais" },
    { code: "327.8", desc: "Influência política, pressão sobre outros Estados" },
    { code: "328", desc: "Parlamentos. Congressos. Governos" },
    { code: "329", desc: "Partidos e movimentos políticos" },
    { code: "33", desc: "Economia. Ciência económica" },
    { code: "330", desc: "Economia em geral" },
    { code: "330.1", desc: "Ciência económica. Teoria, conceitos económicos básicos" },
    { code: "330.3", desc: "Dinâmica da economia. Movimento económico" },
    { code: "330.4", desc: "Economia matemática" },
    { code: "330.5", desc: "Propriedade nacional. Contabilidade nacional" },
    { code: "330.8", desc: "História das teorias, doutrinas, dogmas económicos" },
    { code: "331", desc: "Trabalho. Emprego. Economia do trabalho" },
    { code: "331.1", desc: "Teoria e organização do trabalho" },
    { code: "331.2", desc: "Salários. Ordenados. Remuneração" },
    { code: "331.3", desc: "Outras condições de trabalho, além do salário" },
    { code: "331.4", desc: "Ambiente de trabalho. Segurança e higiene do trabalho" },
    { code: "331.5", desc: "Mercado de trabalho. Emprego" },
    { code: "332", desc: "Economia regional. Economia territorial" },
    { code: "332.1", desc: "Economia regional. Economia territorial" },
    { code: "332.2", desc: "Economia da terra" },
    { code: "332.3", desc: "Utilização da terra" },
    { code: "332.5", desc: "Procura da terra" },
    { code: "332.6", desc: "Valor da terra. Valor da propriedade imóvel" },
    { code: "332.7", desc: "Comércio de terra, de bens imóveis" },
    { code: "332.8", desc: "Economia da habitação" },
    { code: "334", desc: "Formas de organização e cooperação na economia" },
    { code: "336", desc: "Finanças" },
    { code: "336.1", desc: "Finanças públicas. Finanças do governo em geral" },
    { code: "336.2", desc: "Receitas públicas" },
    { code: "336.5", desc: "Despesa pública. Despesa do estado" },
    { code: "336.7", desc: "Moeda. Sistema monetário. Banca. Bolsa de valores" },
    { code: "338", desc: "Situação económica. Política económica. Produção" },
    { code: "338.1", desc: "Situação económica. Ciclo económico" },
    { code: "338.2", desc: "Política económica. Gestão da economia" },
    { code: "338.3", desc: "Produção" },
    { code: "338.4", desc: "Produção e serviços segundo os sectores económicos" },
    { code: "338.48", desc: "Turismo" },
    { code: "338.5", desc: "Preços. Formação de preços. Custos" },
    { code: "339", desc: "Comércio. Relações económicas internacionais" },
    { code: "339.1", desc: "Questões gerais sobre as trocas e o comércio" },
    { code: "339.3", desc: "Comércio interno. Comércio nacional" },
    { code: "339.5", desc: "Comércio externo. Comércio internacional" },
    { code: "339.7", desc: "Finanças internacionais" },
    { code: "339.9", desc: "Economia internacional. Economia global" },
    { code: "34", desc: "Direito. Jurisprudência" },
    { code: "340", desc: "Lei em geral. Métodos jurídicos" },
    { code: "340.1", desc: "Tipos e formas do direito" },
    { code: "340.13", desc: "Direito positivo. Norma legal" },
    { code: "340.14", desc: "Leis não escritas. Leis não estatutárias" },
    { code: "340.5", desc: "Direito comparado" },
    { code: "340.6", desc: "Ciências auxiliares do direito. Medicina legal" },
    { code: "341", desc: "Direito internacional. Direito das nações" },
    { code: "341.1", desc: "Direito das organizações internacionais" },
    { code: "341.2", desc: "Sujeitos e objectos do direito internacional" },
    { code: "341.3", desc: "Direito de guerra" },
    { code: "341.4", desc: "Direito penal internacional" },
    { code: "341.6", desc: "Arbitragem internacional. Adjudicação e jurisdição internacionais" },
    { code: "341.7", desc: "Direito diplomático" },
    { code: "341.8", desc: "Direito consular" },
    { code: "341.9", desc: "Direito internacional privado. Conflitos de leis" },
    { code: "342", desc: "Direito público. Direito constitucional" },
    { code: "342.1", desc: "Estado. Povo. Nação. Poder do Estado" },
    { code: "342.2", desc: "Estado. Estrutura dos estados" },
    { code: "342.3", desc: "Autoridade suprema. Soberania. Formas de Estado" },
    { code: "342.4", desc: "Constituições. Assembleias legislativas" },
    { code: "342.5", desc: "Poderes do Estado" },
    { code: "342.6", desc: "Poder executivo do Estado" },
    { code: "342.7", desc: "Direitos e liberdades fundamentais. Direitos humanos" },
    { code: "342.8", desc: "Lei eleitoral. Votação. Sistemas eleitorais" },
    { code: "342.9", desc: "Direito administrativo" },
    { code: "343", desc: "Direito penal. Delitos penais" },
    { code: "343.1", desc: "Justiça penal. Investigação penal. Processo penal" },
    { code: "343.2", desc: "Direito penal propriamente dito" },
    { code: "343.3", desc: "Crimes contra o Estado" },
    { code: "343.4", desc: "Atentados contra as liberdades fundamentais" },
    { code: "343.5", desc: "Infracções contra a confiança pública, a moral, a família" },
    { code: "343.6", desc: "Infracções contra pessoas" },
    { code: "343.8", desc: "Pena. Execução de sentença" },
    { code: "343.9", desc: "Criminologia. Ciências criminais" },
    { code: "344", desc: "Direito penal especial. Direito penal militar" },
    { code: "346", desc: "Direito económico" },
    { code: "346.2", desc: "Sujeitos do direito económico" },
    { code: "346.3", desc: "Responsabilidades económicas. Contratos económicos" },
    { code: "346.5", desc: "Regulação da ordem económica e seu controlo" },
    { code: "346.6", desc: "Regulação de preços, tarifas, finanças, créditos e contas" },
    { code: "346.7", desc: "Regulação dos sectores individuais da economia" },
    { code: "346.9", desc: "Aplicação do direito económico" },
    { code: "347", desc: "Direito civil" },
    { code: "347.1", desc: "Direito civil em geral" },
    { code: "347.2", desc: "Direitos reais" },
    { code: "347.3", desc: "Bens móveis em geral. Bens mobiliários" },
    { code: "347.4", desc: "Obrigações. Responsabilidade contratual. Contratos" },
    { code: "347.5", desc: "Responsabilidades não contratuais. Danos" },
    { code: "347.6", desc: "Direito da família. Direito das sucessões" },
    { code: "347.7", desc: "Direito comercial. Direito das sociedades" },
    { code: "347.8", desc: "Direito do ar, do espaço, do éter" },
    { code: "347.9", desc: "Direito processual. Organização e pessoal judiciário" },
    { code: "348", desc: "Direito eclesiástico. Direito canónico" },
    { code: "349", desc: "Ramos especiais do direito" },
    { code: "35", desc: "Administração pública. Governo. Assuntos militares" },
    { code: "351", desc: "Actividades específicas da administração pública" },
    { code: "352", desc: "Níveis mais baixos da administração pública. Governo local" },
    { code: "353", desc: "Níveis médios da administração. Governo regional" },
    { code: "353.1", desc: "Divisões primárias do país. Regiões" },
    { code: "353.2", desc: "Governos provinciais. Províncias" },
    { code: "353.5", desc: "Divisões das províncias. Distritos" },
    { code: "353.8", desc: "Tipos especiais da administração regional" },
    { code: "353.9", desc: "Administração independente das regiões de um país" },
    { code: "354", desc: "Nível mais alto da administração. Governo central" },
    { code: "354.1", desc: "Ministérios para assuntos gerais" },
    { code: "355", desc: "Assuntos militares em geral" },
    { code: "355.1", desc: "Forças armadas em geral. Vida militar" },
    { code: "355.2", desc: "Recrutamento de forças. Recrutamento" },
    { code: "355.3", desc: "Organização geral das forças armadas" },
    { code: "355.4", desc: "Operações de guerra em geral. Táctica. Estratégia" },
    { code: "355.5", desc: "Serviços e tácticas de forças e unidades específicas" },
    { code: "355.6", desc: "Administração militar" },
    { code: "355.7", desc: "Estabelecimentos militares. Organização. Funções" },
    { code: "356", desc: "Serviços do exército em geral. Infantaria" },
    { code: "357", desc: "Cavalaria. Tropas montadas. Tropas motorizadas" },
    { code: "358", desc: "Artilharia. Engenharia. Aviação" },
    { code: "358.1", desc: "Artilharia" },
    { code: "358.4", desc: "Aviação militar. Força aérea" },
    { code: "359", desc: "Forças navais. Marinha" },
    { code: "36", desc: "Protecção das necessidades materiais e mentais da vida. Serviço social" },
    { code: "364", desc: "Bem-estar social" },
    { code: "364-1", desc: "Teorias sobre o bem-estar social" },
    { code: "364-2", desc: "Princípios da assistência" },
    { code: "364-3", desc: "Agências de bem-estar social" },
    { code: "364-4", desc: "Pessoas como provedoras de assistência ao bem-estar social" },
    { code: "364-5", desc: "Instalações do bem-estar social" },
    { code: "364-6", desc: "Contribuições e pagamentos" },
    { code: "364-7", desc: "Processos do bem-estar social. Serviços sociais" },
    { code: "364.2", desc: "Necessidades humanas básicas" },
    { code: "364.3", desc: "Benefícios sociais. Segurança social" },
    { code: "364.4", desc: "Áreas de actuação do serviço social" },
    { code: "364.6", desc: "Questões do bem-estar social" },
    { code: "365", desc: "Desejo de habitação e sua satisfação" },
    { code: "366", desc: "Consumerismo" },
    { code: "368", desc: "Seguros" },
    { code: "37", desc: "Educação" },
    { code: "37.01", desc: "Fundamentos da educação. Teoria" },
    { code: "37.02", desc: "Questões gerais de didáctica e método" },
    { code: "37.04", desc: "Educação em relação ao educando" },
    { code: "37.06", desc: "Problemas sociais na educação" },
    { code: "37.07", desc: "Aspectos relacionados com a gestão de instituições de ensino" },
    { code: "37.09", desc: "Organização da instrução" },
    { code: "373", desc: "Tipos de escolas que ministram ensino em geral" },
    { code: "374", desc: "Ensino e formação extra-escolares" },
    { code: "376", desc: "Educação, ensino e treino de grupos especiais" },
    { code: "377", desc: "Ensino especializado. Formação técnica e profissional" },
    { code: "378", desc: "Ensino superior. Universidades" },
    { code: "379.8", desc: "Lazer" },
    { code: "39", desc: "Antropologia cultural. Etnologia. Etnografia" },
    { code: "391", desc: "Vestuário. Indumentária. Moda" },
    { code: "392", desc: "Usos e costumes na vida privada" },
    { code: "393", desc: "Morte. Tratamento de cadáveres. Funerais" },
    { code: "394", desc: "Vida pública. Vida social" },
    { code: "395", desc: "Cerimonial social. Etiqueta" },
    { code: "398", desc: "Folclore em sentido restrito" },
    { code: "5", desc: "Matemática. Ciências Naturais" },
    { code: "502", desc: "O meio ambiente e a sua protecção" },
    { code: "504", desc: "Ameaças ao ambiente" },
    { code: "51", desc: "Matemática" },
    { code: "510", desc: "Considerações fundamentais e gerais das matemáticas" },
    { code: "510.2", desc: "Problemas gerais da lógica matemática" },
    { code: "510.3", desc: "Teoria dos conjuntos" },
    { code: "510.6", desc: "Lógica matemática" },
    { code: "511", desc: "Teoria dos números" },
    { code: "512", desc: "Álgebra" },
    { code: "514", desc: "Geometria" },
    { code: "514.7", desc: "Geometria diferencial" },
    { code: "515.1", desc: "Topologia" },
    { code: "517", desc: "Análise matemática" },
    { code: "517.9", desc: "Equações diferenciais. Equações integrais" },
    { code: "519.1", desc: "Análise combinatória. Teoria dos grafos" },
    { code: "519.2", desc: "Probabilidade. Estatística matemática" },
    { code: "519.6", desc: "Matemática computacional. Análise numérica" },
    { code: "519.7", desc: "Cibernética matemática" },
    { code: "519.8", desc: "Teorias e métodos de investigação operacional matemática" },
    { code: "519.83", desc: "Teoria dos jogos" },
    { code: "519.85", desc: "Programação matemática" },
    { code: "52", desc: "Astronomia. Astrofísica. Geodésia" },
    { code: "520", desc: "Instrumentos e técnicas astronómicas" },
    { code: "521", desc: "Astronomia teórica. Mecânica celeste" },
    { code: "521.9", desc: "Astrometria. Astronomia esférica" },
    { code: "523", desc: "O sistema solar" },
    { code: "523.3", desc: "Sistema Terra-Lua" },
    { code: "523.4", desc: "Planetas e seus satélites. Planetologia" },
    { code: "523.6", desc: "Meio interplanetário. Cometas. Meteoros" },
    { code: "523.9", desc: "O Sol. Física solar" },
    { code: "524", desc: "Estrelas. Sistemas estelares. O Universo" },
    { code: "524.1", desc: "Raios cósmicos" },
    { code: "524.3", desc: "Estrelas" },
    { code: "524.4", desc: "Aglomerados de estrelas. Associações de estrelas" },
    { code: "524.5", desc: "Meio interestelar. Nebulosas galácticas" },
    { code: "524.6", desc: "A Galáxia (Via Láctea)" },
    { code: "524.7", desc: "Sistemas extragalácticos" },
    { code: "524.8", desc: "O Universo. Metagaláxia. Cosmologia" },
    { code: "528", desc: "Geodésia. Levantamento. Fotogrametria. Cartografia" },
    { code: "528.1", desc: "Teoria dos erros e da correcção na geodésia" },
    { code: "528.2", desc: "Forma da Terra. Medição da Terra" },
    { code: "528.3", desc: "Levantamento geodésico" },
    { code: "528.4", desc: "Levantamentos de campo. Topografia" },
    { code: "528.5", desc: "Instrumentos e equipamentos geodésicos" },
    { code: "528.7", desc: "Fotogrametria: aérea, terrestre" },
    { code: "528.8", desc: "Captação remota de dados" },
    { code: "528.9", desc: "Cartografia" },
    { code: "53", desc: "Física" },
    { code: "53.01", desc: "Teoria e natureza dos fenómenos" },
    { code: "53.02", desc: "Leis gerais dos fenómenos" },
    { code: "53.03", desc: "Produção e causas dos fenómenos" },
    { code: "53.04", desc: "Efeitos dos fenómenos" },
    { code: "53.05", desc: "Observação e registo dos fenómenos" },
    { code: "53.06", desc: "Aplicação, utilização dos fenómenos" },
    { code: "53.07", desc: "Aparelhos para produção e estudo dos fenómenos" },
    { code: "53.08", desc: "Princípios gerais e teoria da medição" },
    { code: "53.09", desc: "Dependência de fenómenos relativos a determinados efeitos" },
    { code: "531", desc: "Mecânica em geral. Mecânica dos corpos sólidos" },
    { code: "531.1", desc: "Cinemática" },
    { code: "531.2", desc: "Estática. Forças. Equilíbrio" },
    { code: "531.3", desc: "Dinâmica. Cinética" },
    { code: "531.4", desc: "Trabalho. Peso. Massa. Fricção" },
    { code: "531.5", desc: "Gravidade. Gravitação. Pêndulos. Balística" },
    { code: "531.6", desc: "Energia mecânica" },
    { code: "531.7", desc: "Medição de quantidades geométricas e mecânicas" },
    { code: "531.8", desc: "Teoria das máquinas. Mecânica técnica" },
    { code: "532", desc: "Mecânica dos fluídos em geral. Hidromecânica" },
    { code: "532.1", desc: "Hidrostática em geral" },
    { code: "532.2", desc: "Equilíbrio dos líquidos" },
    { code: "532.3", desc: "Corpos imersos. Corpos flutuantes" },
    { code: "532.5", desc: "Movimentos dos líquidos. Hidrodinâmica" },
    { code: "532.6", desc: "Fenómenos de superfície. Tensão superficial" },
    { code: "532.7", desc: "Teoria cinética dos líquidos. Osmose" },
    { code: "533", desc: "Mecânica dos gases. Aeromecânica. Física do plasma" },
    { code: "533.1", desc: "Propriedades dos gases" },
    { code: "533.2", desc: "Elasticidade. Compressibilidade. Liquefacção" },
    { code: "533.5", desc: "Gases rarefeitos. Física do vácuo" },
    { code: "533.6", desc: "Aerodinâmica" },
    { code: "533.7", desc: "Teoria cinética dos gases" },
    { code: "533.9", desc: "Física do plasma" },
    { code: "534", desc: "Vibrações. Ondas. Acústica" },
    { code: "534.1", desc: "Vibração de corpos" },
    { code: "534.2", desc: "Propagação das vibrações" },
    { code: "534.3", desc: "Sons e percepção musical" },
    { code: "534.4", desc: "Análise e síntese de sons" },
    { code: "534.5", desc: "Composição das vibrações" },
    { code: "534.6", desc: "Medições acústicas" },
    { code: "534.7", desc: "Acústica fisiológica. Acústica médica" },
    { code: "534.8", desc: "Aplicações da acústica" },
    { code: "535", desc: "Óptica" },
    { code: "535.1", desc: "Teoria da luz" },
    { code: "535.2", desc: "Propagação e energética da radiação. Fotometria" },
    { code: "535.3", desc: "Propagação. Reflexão. Refracção" },
    { code: "535.4", desc: "Interferência. Difracção" },
    { code: "535.5", desc: "Polarização. Dupla Refracção" },
    { code: "535.6", desc: "Cores e suas propriedades. Teoria da cor" },
    { code: "535.8", desc: "Aplicações da óptica em geral" },
    { code: "536", desc: "Calor. Termodinâmica" },
    { code: "536.1", desc: "Teoria geral do calor" },
    { code: "536.2", desc: "Condução de calor. Transferência de calor" },
    { code: "536.3", desc: "Efeito dos corpos sobre a radiação térmica" },
    { code: "536.4", desc: "Efeito da entrada de calor e da temperatura" },
    { code: "536.5", desc: "Temperatura. Medição de temperatura" },
    { code: "536.6", desc: "Calorimetria" },
    { code: "536.7", desc: "Termodinâmica. Energética" },
    { code: "537", desc: "Electricidade. Magnetismo. Electromagnetismo" },
    { code: "537.2", desc: "Electricidade estática. Electroestática" },
    { code: "537.3", desc: "Electricidade de corrente. Corrente eléctrica" },
    { code: "537.5", desc: "Fenómenos do electrão e do ião" },
    { code: "537.6", desc: "Magnetismo" },
    { code: "537.8", desc: "Electromagnetismo. Electrodinâmica" },
    { code: "538.9", desc: "Física da matéria condensada. Física do estado sólido" },
    { code: "539", desc: "Natureza física da matéria" },
    { code: "539.1", desc: "Física nuclear. Física atómica. Física molecular" },
    { code: "539.2", desc: "Propriedades e estruturas dos sistemas moleculares" },
    { code: "539.3", desc: "Elasticidade. Deformação. Mecânica de sólidos elásticos" },
    { code: "539.4", desc: "Força. Resistência à tensão" },
    { code: "539.5", desc: "Propriedades dos materiais que afectam a deformabilidade" },
    { code: "539.6", desc: "Forças intermoleculares" },
    { code: "539.8", desc: "Outros efeitos físico-mecânicos" },
    { code: "54", desc: "Química. Cristalografia. Mineralogia" },
    { code: "542", desc: "Química prática de laboratório" },
    { code: "542.1", desc: "Laboratórios químicos" },
    { code: "542.2", desc: "Aparelhos e técnicas de laboratório em geral" },
    { code: "542.3", desc: "Medição de peso, massa, volume" },
    { code: "542.4", desc: "Aplicação de calor e frio" },
    { code: "542.5", desc: "Uso de chamas" },
    { code: "542.6", desc: "Trabalho com líquidos" },
    { code: "542.7", desc: "Trabalhos com gases" },
    { code: "542.8", desc: "Operações físicas, físico-químicas e eléctricas" },
    { code: "542.9", desc: "Reacções químicas" },
    { code: "543", desc: "Química analítica" },
    { code: "543.2", desc: "Métodos químicos de análise" },
    { code: "543.3", desc: "Amostragem e análise da água" },
    { code: "543.4", desc: "Métodos de análise espectral" },
    { code: "543.5", desc: "Métodos físico-químicos de análise" },
    { code: "543.6", desc: "Análise de diferentes substâncias" },
    { code: "543.9", desc: "Análise por reacções biológicas e bioquímicas" },
    { code: "544", desc: "Química física" },
    { code: "544.1", desc: "Estrutura química da matéria" },
    { code: "544.2", desc: "Química física dos sólidos, dos líquidos e dos gases" },
    { code: "544.3", desc: "Termodinâmica química" },
    { code: "544.4", desc: "Cinética química. Catálise" },
    { code: "544.5", desc: "Química dos processos de alta energia" },
    { code: "544.6", desc: "Electroquímica" },
    { code: "544.7", desc: "Química dos fenómenos de superfície e colóides" },
    { code: "546", desc: "Química inorgânica" },
    { code: "546.1", desc: "Não metais e metalóides em geral" },
    { code: "546.3", desc: "Metais em geral" },
    { code: "547", desc: "Química orgânica" },
    { code: "547.1", desc: "Classificação dos compostos orgânicos" },
    { code: "548", desc: "Cristalografia" },
    { code: "548.1", desc: "Cristalografia matemática" },
    { code: "548.2", desc: "Crescimento do cristal" },
    { code: "548.3", desc: "Química dos cristais" },
    { code: "548.4", desc: "Irregularidades nos cristais" },
    { code: "548.5", desc: "Formação, crescimento e dissolução dos cristais" },
    { code: "548.7", desc: "Estrutura fina dos cristais" },
    { code: "549", desc: "Mineralogia" },
    { code: "549.2", desc: "Elementos e ligas naturais" },
    { code: "549.3", desc: "Sulfetos. Sulfossais" },
    { code: "549.4", desc: "Haletos. Halóides" },
    { code: "549.5", desc: "Compostos de oxigénio" },
    { code: "549.6", desc: "Silicatos. Titanatos. Zirconatos" },
    { code: "549.7", desc: "Outros compostos de oxiácidos" },
    { code: "549.8", desc: "Minerais orgânicos" },
    { code: "55", desc: "Ciências da terra. Geologia" },
    { code: "550", desc: "Ciências auxiliares da geologia" },
    { code: "550.1", desc: "Fisiografia" },
    { code: "550.2", desc: "Geoastronomia. Cosmogonia" },
    { code: "550.3", desc: "Geofísica" },
    { code: "550.4", desc: "Geoquímica" },
    { code: "550.7", desc: "Geobiologia" },
    { code: "550.8", desc: "Geologia e geofísica aplicada. Prospecção" },
    { code: "550.93", desc: "Geocronologia. Datação geológica" },
    { code: "551", desc: "Geologia geral. Meteorologia. Climatologia" },
    { code: "551.1", desc: "Estrutura geral da Terra" },
    { code: "551.2", desc: "Geodinâmica interna (processos endógenos)" },
    { code: "551.21", desc: "Vulcanicidade. Vulcanismo" },
    { code: "551.24", desc: "Geotectónica" },
    { code: "551.3", desc: "Geodinâmica externa (processos exógenos)" },
    { code: "551.32", desc: "Glaciologia" },
    { code: "551.4", desc: "Geomorfologia" },
    { code: "551.44", desc: "Espeleologia. Cavernas" },
    { code: "551.46", desc: "Oceanografia física" },
    { code: "551.58", desc: "Climatologia" },
    { code: "551.7", desc: "Geologia histórica. Estratigrafia" },
    { code: "551.8", desc: "Paleogeografia" },
    { code: "552", desc: "Petrologia. Petrografia" },
    { code: "552.1", desc: "Características e propriedades em geral das rochas" },
    { code: "552.3", desc: "Rochas magmáticas. Rochas ígneas" },
    { code: "552.4", desc: "Rochas metamórficas" },
    { code: "552.5", desc: "Rochas sedimentares" },
    { code: "552.6", desc: "Meteoritos" },
    { code: "553", desc: "Geologia económica. Depósitos minerais" },
    { code: "553.2", desc: "Formação do minério" },
    { code: "553.3", desc: "Depósitos de minério em geral" },
    { code: "553.4", desc: "Outros depósitos de minérios" },
    { code: "553.5", desc: "Depósitos de pedra natural" },
    { code: "553.6", desc: "Depósitos de vários minerais e terras inorgânicas" },
    { code: "553.7", desc: "Fontes minerais" },
    { code: "553.8", desc: "Depósitos de pedras preciosas e semipreciosas" },
    { code: "553.9", desc: "Depósitos de rochas carbonáceas" },
    { code: "556", desc: "Hidrosfera. Hidrologia" },
    { code: "556.3", desc: "Hidrologia das águas subterrâneas. Hidrogeologia" },
    { code: "556.5", desc: "Hidrologia da água de superfície" },
    { code: "56", desc: "Paleontologia" },
    { code: "57", desc: "Ciências biológicas em geral" },
    { code: "57.01", desc: "Leis gerais. Aspectos teóricos" },
    { code: "57.02", desc: "Processos biológicos e etológicos" },
    { code: "57.03", desc: "Padrão das variações de propriedade" },
    { code: "57.04", desc: "Factores. Influências" },
    { code: "57.05", desc: "Características dependentes do controlo central" },
    { code: "57.06", desc: "Nomenclatura e classificação de organismos" },
    { code: "57.07", desc: "Paleontologia analítica" },
    { code: "57.08", desc: "Técnicas biológicas. Métodos experimentais" },
    { code: "572", desc: "Antropologia física" },
    { code: "572.1", desc: "Antropogenia. Origem da espécie humana" },
    { code: "572.9", desc: "Antropogeografia especial" },
    { code: "573", desc: "Biologia geral e teórica" },
    { code: "574", desc: "Ecologia geral e biodiversidade" },
    { code: "575", desc: "Genética geral" },
    { code: "576", desc: "Biologia celular e subcelular. Citologia" },
    { code: "577", desc: "Bases materiais da vida. Bioquímica. Biofísica" },
    { code: "578", desc: "Virologia" },
    { code: "579", desc: "Microbiologia" },
    { code: "579.2", desc: "Microbiologia geral" },
    { code: "579.6", desc: "Microbiologia aplicada" },
    { code: "579.8", desc: "Microrganismos. Bactéria" },
    { code: "58", desc: "Botânica" },
    { code: "581", desc: "Botânica geral" },
    { code: "581.1", desc: "Fisiologia vegetal" },
    { code: "581.2", desc: "Doenças das plantas. Fitopatologia" },
    { code: "581.3", desc: "Embriologia vegetal" },
    { code: "581.4", desc: "Morfologia vegetal. Anatomia vegetal" },
    { code: "581.5", desc: "Hábitos das plantas. Ecologia vegetal" },
    { code: "581.6", desc: "Botânica aplicada. Uso de plantas" },
    { code: "581.8", desc: "Histologia vegetal" },
    { code: "581.9", desc: "Botânica geográfica" },
    { code: "582", desc: "Botânica sistemática" },
    { code: "582.091", desc: "Árvores" },
    { code: "582.093", desc: "Arbustos" },
    { code: "582.095", desc: "Crescimento subterrâneo" },
    { code: "582.097", desc: "Plantas trepadoras lenhosas" },
    { code: "582.099", desc: "Plantas herbáceas ou não-lenhosas" },
    { code: "582.23", desc: "Bacteria" },
    { code: "582.24", desc: "Protista. Chromista" },
    { code: "582.261", desc: "Algae (algas)" },
    { code: "582.28", desc: "Fungos" },
    { code: "582.29", desc: "Líquenes" },
    { code: "582.32", desc: "Bryophyta (briófitas)" },
    { code: "582.361", desc: "Tracheophyta (plantas vasculares)" },
    { code: "582.37", desc: "Pteridophyta (pteridófitos). Fetos" },
    { code: "582.4", desc: "Spermatophyta (plantas com semente)" },
    { code: "582.42", desc: "Gymnosperms (gimnospermas)" },
    { code: "582.44", desc: "Cycadophyta (cicadófita)" },
    { code: "582.46", desc: "Ginkgophyta" },
    { code: "582.47", desc: "Pinophyta / Coniferae (coníferas)" },
    { code: "582.5", desc: "Magnoliophyta (angiospermes)" },
    { code: "582.51", desc: "Arecales (palmeira). Pandanales" },
    { code: "582.53", desc: "Alismatales" },
    { code: "582.54", desc: "Poales" },
    { code: "582.56", desc: "Zingiberales" },
    { code: "582.57", desc: "Liliales" },
    { code: "582.58", desc: "Asparagales" },
    { code: "582.6", desc: "Dicotyledoneae (dicotiledóneas)" },
    { code: "582.62", desc: "Fagales" },
    { code: "582.63", desc: "Rosales" },
    { code: "582.65", desc: "Nymphaeales" },
    { code: "582.66", desc: "Caryophyllales" },
    { code: "582.67", desc: "Magnoliids" },
    { code: "582.68", desc: "Dilleniidae" },
    { code: "582.7", desc: "Rosidae" },
    { code: "582.82", desc: "Vitales" },
    { code: "582.9", desc: "Asteridae" },
    { code: "59", desc: "Zoologia" },
    { code: "591", desc: "Zoologia geral" },
    { code: "591.1", desc: "Fisiologia animal" },
    { code: "591.2", desc: "Doenças de animais" },
    { code: "591.3", desc: "Embriologia animal" },
    { code: "591.4", desc: "Anatomia animal" },
    { code: "591.5", desc: "Hábitos animais. Ecologia. Etologia" },
    { code: "591.6", desc: "Zoologia económica. Zoologia aplicada" },
    { code: "591.8", desc: "Histologia animal" },
    { code: "591.9", desc: "Zoologia geográfica. Fauna" },
    { code: "592", desc: "Invertebrata. Invertebrados em geral" },
    { code: "593.1", desc: "Protozoários" },
    { code: "593.4", desc: "Poríferos (esponjas)" },
    { code: "594", desc: "Moluscos. Briozoários. Braquiópodes" },
    { code: "595", desc: "Articulata" },
    { code: "595.7", desc: "Insecta. Insectos. Entomologia" },
    { code: "596", desc: "Chordata. Cordados" },
    { code: "596.2", desc: "Urocordados (tunicados)" },
    { code: "597", desc: "Vertebrata. Vertebrados. Pisces. Peixes" },
    { code: "597.3", desc: "Peixes cartilaginosos" },
    { code: "597.4", desc: "Osteichthyes (peixes ósseos)" },
    { code: "597.6", desc: "Amphibia. Anfíbios" },
    { code: "598", desc: "Sauropsídeos" },
    { code: "598.1", desc: "Reptilia. Répteis" },
    { code: "598.2", desc: "Aves. Ornitologia" },
    { code: "599", desc: "Mammalia (mamíferos)" },
    { code: "599.1", desc: "Prototheria" },
    { code: "599.2", desc: "Metatheria. Marsupiais" },
    { code: "599.3", desc: "Eutheria (mamíferos placentários)" },
    { code: "599.31", desc: "Pholidota" },
    { code: "599.32", desc: "Rodentia (roedores)" },
    { code: "599.35", desc: "Insectivora (insectívoros)" },
    { code: "599.4", desc: "Chiroptera (morcegos)" },
    { code: "599.5", desc: "Cetáceos" },
    { code: "599.61", desc: "Proboscidea (elefantes)" },
    { code: "599.72", desc: "Perissodactyla (ungulados de dedos ímpares)" },
    { code: "599.73", desc: "Artiodactyla (ungulados de dedos pares)" },
    { code: "599.74", desc: "Carnivora (carnívoros)" },
    { code: "599.8", desc: "Primates (primatas)" },
    { code: "6", desc: "Ciências aplicadas. Medicina. Tecnologia" },
    { code: "60", desc: "Biotecnologia" },
    { code: "601", desc: "Conceitos fundamentais" },
    { code: "602", desc: "Processos e técnicas em biotecnologia" },
    { code: "604", desc: "Produtos biotecnológicos" },
    { code: "606", desc: "Aplicações da biotecnologia" },
    { code: "608", desc: "Problemas em biotecnologia" },
    { code: "61", desc: "Ciências médicas" },
    { code: "611", desc: "Anatomia. Anatomia humana" },
    { code: "612", desc: "Fisiologia. Fisiologia humana" },
    { code: "612.1", desc: "Sangue. Sistema cardiovascular" },
    { code: "612.2", desc: "Respiração. Sistema respiratório" },
    { code: "612.3", desc: "Alimentação. Digestão" },
    { code: "612.4", desc: "Sistema glandular" },
    { code: "612.5", desc: "Calor animal" },
    { code: "612.6", desc: "Reprodução. Crescimento" },
    { code: "612.7", desc: "Funções motoras" },
    { code: "612.8", desc: "Sistema nervoso. Órgãos sensoriais" },
    { code: "613", desc: "Higiene em geral. Saúde pessoal" },
    { code: "613.2", desc: "Dietética" },
    { code: "613.4", desc: "Higiene pessoal" },
    { code: "613.6", desc: "Saúde ocupacional" },
    { code: "613.7", desc: "Saúde e higiene dos tempos livres" },
    { code: "613.8", desc: "Saúde e higiene do sistema nervoso" },
    { code: "614", desc: "Saúde e higiene públicas" },
    { code: "614.2", desc: "Organização pública e profissional da saúde" },
    { code: "614.4", desc: "Controlo e prevenção de doenças transmissíveis" },
    { code: "614.7", desc: "Higiene do ar, água, solo. Poluição" },
    { code: "614.8", desc: "Acidentes. Segurança" },
    { code: "614.9", desc: "Saúde dos animais" },
    { code: "615", desc: "Farmacologia. Terapêutica. Toxicologia" },
    { code: "615.1", desc: "Farmácia geral e profissional" },
    { code: "615.8", desc: "Fisioterapia. Radioterapia" },
    { code: "616", desc: "Patologia. Medicina clínica" },
    { code: "616-001", desc: "Traumatismos. Feridas" },
    { code: "616-002", desc: "Inflamação" },
    { code: "616-006", desc: "Tumores. Oncologia" },
    { code: "616-007", desc: "Malformações" },
    { code: "616-009", desc: "Distúrbios nervosos" },
    { code: "616-05", desc: "Pessoas e características pessoais em patologia" },
    { code: "616-07", desc: "Semiologia. Diagnóstico" },
    { code: "616-08", desc: "Tratamento" },
    { code: "616.1", desc: "Patologia do sistema circulatório" },
    { code: "616.2", desc: "Patologia do sistema respiratório" },
    { code: "616.3", desc: "Patologia do sistema digestivo" },
    { code: "616.31", desc: "Estomatologia. Doenças da boca e dos dentes" },
    { code: "616.5", desc: "Dermatologia clínica. Doenças cutâneas" },
    { code: "616.6", desc: "Patologias do sistema urogenital" },
    { code: "616.7", desc: "Patologia dos órgãos da locomoção" },
    { code: "616.8", desc: "Neurologia. Psiquiatria" },
    { code: "616.9", desc: "Doenças transmissíveis. Doenças infecciosas" },
    { code: "617", desc: "Cirurgia. Ortopedia. Oftalmologia" },
    { code: "618", desc: "Ginecologia. Obstetrícia" },
    { code: "62", desc: "Engenharia. Tecnologia em geral" },
    { code: "620", desc: "Testes dos materiais. Economia de energia" },
    { code: "620.3", desc: "Nanotecnologia" },
    { code: "621", desc: "Engenharia mecânica em geral. Engenharia eléctrica" },
    { code: "621.1", desc: "Máquinas térmicas. Máquinas a vapor" },
    { code: "621.22", desc: "Energia hidráulica" },
    { code: "621.3", desc: "Engenharia eléctrica" },
    { code: "621.4", desc: "Motores térmicos" },
    { code: "621.5", desc: "Energia pneumática. Refrigeração" },
    { code: "621.6", desc: "Manipulação e distribuição de fluidos" },
    { code: "621.7", desc: "Tecnologia mecânica em geral" },
    { code: "621.8", desc: "Elementos das máquinas" },
    { code: "621.9", desc: "Trabalho à máquina" },
    { code: "622", desc: "Mineração" },
    { code: "622.1", desc: "Estudo e levantamento da mina" },
    { code: "622.2", desc: "Operações de mineração" },
    { code: "622.3", desc: "Mineração de minerais específicos" },
    { code: "622.7", desc: "Processamento de minerais" },
    { code: "623", desc: "Engenharia militar" },
    { code: "623.1", desc: "Fortificações" },
    { code: "623.4", desc: "Armamentos. Material militar" },
    { code: "623.7", desc: "Aviação militar e naval" },
    { code: "623.8", desc: "Engenharia naval. Construção naval" },
    { code: "624", desc: "Engenharia civil e de estruturas em geral" },
    { code: "624.01", desc: "Estruturas segundo o material" },
    { code: "624.1", desc: "Terraplanagem. Fundações. Túneis" },
    { code: "624.21", desc: "Construção de pontes" },
    { code: "625", desc: "Engenharia do transporte terrestre" },
    { code: "625.1", desc: "Ferrovias em geral" },
    { code: "625.7", desc: "Rodovias em geral. Estradas" },
    { code: "626", desc: "Engenharia hidráulica em geral" },
    { code: "627", desc: "Engenharia de cursos de água naturais. Portos" },
    { code: "627.8", desc: "Represas. Centrais hidroeléctricas" },
    { code: "628", desc: "Engenharia de saúde pública. Saneamento" },
    { code: "628.1", desc: "Abastecimento de água" },
    { code: "628.2", desc: "Drenagem urbana. Esgotos" },
    { code: "628.4", desc: "Higiene urbana. Resíduos. Lixo" },
    { code: "628.9", desc: "Iluminação" },
    { code: "629", desc: "Engenharia de veículos de transporte" },
    { code: "629.3", desc: "Engenharia de veículos terrestres" },
    { code: "629.4", desc: "Engenharia de veículos ferroviários" },
    { code: "629.5", desc: "Engenharia naval. Construção de navios" },
    { code: "629.7", desc: "Engenharia de transportes aéreo e espacial. Aeronáutica" },
    { code: "63", desc: "Agricultura. Ciências agrárias" },
    { code: "630", desc: "Silvicultura. Florestas" },
    { code: "631", desc: "Agricultura em geral. Agronomia" },
    { code: "631.1", desc: "Gestão de propriedades agrícolas" },
    { code: "631.3", desc: "Máquinas e equipamento agrícola" },
    { code: "631.4", desc: "Ciências do solo. Pedologia" },
    { code: "631.8", desc: "Fertilizantes" },
    { code: "632", desc: "Doenças das plantas. Pragas" },
    { code: "633", desc: "Culturas e sua produção" },
    { code: "633.1", desc: "Cereais" },
    { code: "634", desc: "Fruticultura" },
    { code: "634.8", desc: "Viticultura" },
    { code: "635", desc: "Horticultura. Jardinagem" },
    { code: "636", desc: "Criação de animais. Pecuária" },
    { code: "636.09", desc: "Medicina veterinária" },
    { code: "637", desc: "Produtos de animais domésticos" },
    { code: "639", desc: "Caça. Pesca. Piscicultura" },
    { code: "64", desc: "Economia doméstica" },
    { code: "641", desc: "Alimentos. Culinária" },
    { code: "643", desc: "A casa. A residência" },
    { code: "646", desc: "Roupa. Cuidado com o corpo" },
    { code: "65", desc: "Indústrias da comunicação e dos transportes. Contabilidade" },
    { code: "654", desc: "Telecomunicação" },
    { code: "655", desc: "Indústrias gráficas. Edição" },
    { code: "656", desc: "Serviços de transporte. Tráfego" },
    { code: "657", desc: "Contabilidade" },
    { code: "658", desc: "Gestão, administração de empresas" },
    { code: "658.3", desc: "Recursos humanos" },
    { code: "658.8", desc: "Marketing. Vendas" },
    { code: "659", desc: "Publicidade. Relações públicas" },
    { code: "66", desc: "Tecnologia química" },
    { code: "661", desc: "Químicos" },
    { code: "662", desc: "Explosivos. Combustíveis" },
    { code: "663", desc: "Microbiologia industrial. Bebidas" },
    { code: "663.2", desc: "Vinhos. Enologia" },
    { code: "664", desc: "Produção de alimentos" },
    { code: "665", desc: "Óleos. Gorduras. Ceras. Petróleo" },
    { code: "666", desc: "Indústria do vidro. Cerâmica. Cimento" },
    { code: "667", desc: "Indústrias de corantes. Tintas" },
    { code: "669", desc: "Metalurgia. Siderurgia" },
    { code: "67", desc: "Indústria, artes industriais e ofícios diversos" },
    { code: "671", desc: "Metais preciosos. Joalharia" },
    { code: "672", desc: "Artigos de ferro e aço" },
    { code: "674", desc: "Indústria da madeira" },
    { code: "675", desc: "Indústria do couro" },
    { code: "676", desc: "Indústria do papel" },
    { code: "677", desc: "Indústria têxtil" },
    { code: "678", desc: "Borracha. Plásticos" },
    { code: "68", desc: "Indústrias de artigos acabados ou montados" },
    { code: "681", desc: "Mecanismos e instrumentos de precisão" },
    { code: "681.5", desc: "Engenharia de controle automático" },
    { code: "681.6", desc: "Máquinas de reprodução gráfica" },
    { code: "687", desc: "Indústria do vestuário" },
    { code: "69", desc: "Indústria da construção" },
    { code: "691", desc: "Materiais de construção" },
    { code: "7", desc: "Arte. Recreação. Desporto" },
    { code: "7.01", desc: "Teoria e filosofia da arte" },
    { code: "7.03", desc: "Períodos e fases artísticas. Estilos" },
    { code: "71", desc: "Planeamento territorial. Urbanismo" },
    { code: "711", desc: "Planeamento regional, urbano e rural" },
    { code: "712", desc: "Planeamento da paisagem. Parques. Jardins" },
    { code: "72", desc: "Arquitectura" },
    { code: "721", desc: "Edifícios em geral" },
    { code: "725", desc: "Edifícios públicos, comerciais e industriais" },
    { code: "726", desc: "Arquitectura religiosa" },
    { code: "728", desc: "Arquitectura da habitação" },
    { code: "73", desc: "Artes plásticas. Escultura" },
    { code: "737", desc: "Numismática" },
    { code: "738", desc: "Cerâmica artística" },
    { code: "739", desc: "Arte do metal. Ourivesaria" },
    { code: "74", desc: "Desenho. Design. Artes aplicadas" },
    { code: "741", desc: "Desenho em geral" },
    { code: "744", desc: "Desenho técnico" },
    { code: "745", desc: "Artes decorativas, artesanato" },
    { code: "75", desc: "Pintura" },
    { code: "76", desc: "Artes gráficas. Gravura" },
    { code: "77", desc: "Fotografia" },
    { code: "78", desc: "Música" },
    { code: "78.01", desc: "Teoria e filosofia da música" },
    { code: "782", desc: "Música dramática. Ópera" },
    { code: "784", desc: "Música vocal" },
    { code: "785", desc: "Música instrumental" },
    { code: "79", desc: "Divertimentos. Espectáculos. Jogos. Desportos" },
    { code: "791", desc: "Cinema. Filmes" },
    { code: "792", desc: "Teatro" },
    { code: "793", desc: "Divertimentos sociais. Dança" },
    { code: "794", desc: "Jogos de mesa. Xadrez" },
    { code: "796", desc: "Desporto. Jogos. Exercícios físicos" },
    { code: "796.3", desc: "Jogos de bola" },
    { code: "796.4", desc: "Ginástica. Atletismo" },
    { code: "797", desc: "Desportos aquáticos e aéreos" },
    { code: "798", desc: "Equitação e hipismo" },
    { code: "799", desc: "Pesca desportiva. Caça desportiva" },
    { code: "8", desc: "Língua. Linguística. Literatura" },
    { code: "80", desc: "Filologia. Questões gerais" },
    { code: "801", desc: "Prosódia" },
    { code: "808", desc: "Retórica" },
    { code: "81", desc: "Linguística e línguas" },
    { code: "811", desc: "Línguas individuais" },
    { code: "811.111", desc: "Inglês" },
    { code: "811.112.2", desc: "Alemão" },
    { code: "811.133.1", desc: "Francês" },
    { code: "811.134.2", desc: "Espanhol" },
    { code: "811.134.3", desc: "Português" },
    { code: "82", desc: "Literatura" },
    { code: "82-1", desc: "Poesia" },
    { code: "82-2", desc: "Drama. Peças de teatro" },
    { code: "82-3", desc: "Ficção. Romance" },
    { code: "821", desc: "Literaturas de línguas individuais" },
    { code: "821.134.3", desc: "Literatura portuguesa" },
    { code: "9", desc: "Geografia. Biografia. História" },
    { code: "902", desc: "Arqueologia" },
    { code: "903", desc: "Pré-história" },
    { code: "908", desc: "Estudos regionais" },
    { code: "91", desc: "Geografia. Exploração" },
    { code: "911", desc: "Geografia geral" },
    { code: "912", desc: "Mapas. Atlas" },
    { code: "913", desc: "Geografia regional" },
    { code: "92", desc: "Estudos biográficos. Genealogia" },
    { code: "929", desc: "Biografias" },
    { code: "929.5", desc: "Genealogia" },
    { code: "929.6", desc: "Heráldica" },
    { code: "929.9", desc: "Bandeiras" },
    { code: "93", desc: "História (ciência histórica)" },
    { code: "930", desc: "Ciência histórica. Arquivística" },
    { code: "94", desc: "História em geral" }
];
