const cddDatabase = {
    // --- 000: GENERALIDADES & COMPUTAÇÃO ---
    "000": "Generalidades e Ciência da Computação",
    "001": "Conhecimento",
    "002": "O livro",
    "003": "Sistemas",
    "004": "Processamento de dados e Ciência da Computação",
    "004.6": "Redes de computadores",
    "005": "Programação, software e dados",
    "005.1": "Desenvolvimento de software",
    "006": "Métodos especiais (IA, Gráficos)",
    "010": "Bibliografia",
    "020": "Biblioteconomia e Ciência da Informação",
    "030": "Enciclopédias gerais",
    "050": "Publicações seriadas e revistas",
    "060": "Organizações gerais e museologia",
    "070": "Mídia noticiosa, jornalismo, publicações",
    "080": "Coleções gerais",
    "090": "Manuscritos e livros raros",

    // --- 100: FILOSOFIA & PSICOLOGIA ---
    "100": "Filosofia e psicologia",
    "110": "Metafísica",
    "120": "Epistemologia, causalidade, gênero humano",
    "130": "Parapsicologia e ocultismo",
    "133": "Tópicos específicos em parapsicologia e ocultismo",
    "140": "Escolas filosóficas específicas",
    "150": "Psicologia",
    "152": "Percepção, movimento, emoções",
    "153": "Processos mentais e inteligência",
    "154": "Subconsciente e estados alterados",
    "155": "Psicologia diferencial e do desenvolvimento",
    "158": "Psicologia aplicada (Autoajuda)",
    "160": "Lógica",
    "170": "Ética (Filosofia moral)",
    "180": "Filosofia antiga, medieval e oriental",
    "190": "Filosofia ocidental moderna",

    // --- 200: RELIGIÃO ---
    "200": "Religião",
    "210": "Filosofia e teoria da religião",
    "220": "Bíblia",
    "221": "Antigo Testamento",
    "225": "Novo Testamento",
    "230": "Cristianismo e teologia cristã",
    "240": "Moral cristã e teologia devocional",
    "250": "Ordens cristãs e igreja local",
    "260": "Teologia social e eclesiologia",
    "270": "História do cristianismo",
    "280": "Denominações e seitas cristãs",
    "290": "Outras religiões",
    "294": "Religiões de origem indiana (Budismo, Hinduísmo)",
    "296": "Judaísmo",
    "297": "Islamisno",

    // --- 300: CIÊNCIAS SOCIAIS ---
    "300": "Ciências sociais",
    "301": "Sociologia e antropologia",
    "302": "Interação social",
    "303": "Processos sociais (Guerra, Conflito)",
    "304": "Fatores que afetam o comportamento social",
    "305": "Grupos sociais (Jovens, Idosos, Mulheres)",
    "306": "Cultura e instituições",
    "310": "Estatísticas gerais",
    "320": "Ciência política",
    "327": "Relações internacionais",
    "330": "Economia",
    "331": "Economia do trabalho",
    "332": "Economia financeira (Bancos, Dinheiro)",
    "336": "Finanças públicas",
    "340": "Direito",
    "341": "Direito internacional",
    "342": "Direito constitucional e administrativo",
    "343": "Direito militar, tributário, comercial",
    "344": "Direito do trabalho, social, educação",
    "345": "Direito penal",
    "346": "Direito privado (Civil)",
    "347": "Processo civil e tribunais",
    "350": "Administração pública e ciência militar",
    "360": "Problemas e serviços sociais",
    "362": "Serviços de bem-estar social",
    "364": "Criminologia",
    "370": "Educação",
    "371": "Gestão escolar e educação especial",
    "372": "Ensino fundamental",
    "373": "Ensino médio",
    "378": "Ensino superior",
    "380": "Comércio, comunicações e transporte",
    "390": "Costumes, etiqueta e folclore",

    // --- 400: LINGUAGEM ---
    "400": "Linguagem",
    "410": "Linguística",
    "419": "Linguagem de sinais",
    "420": "Inglês e inglês antigo",
    "430": "Línguas germânicas (Alemão)",
    "440": "Línguas românicas (Francês)",
    "450": "Italiano, romeno",
    "460": "Espanhol e Português",
    "469": "Português",
    "470": "Línguas itálicas (Latim)",
    "480": "Línguas helênicas (Grego)",
    "490": "Outras línguas",
// --- 500: CIÊNCIAS NATURAIS ---
    "500": "Ciências naturais e matemática",
    "510": "Matemática",
    "511": "Princípios gerais da matemática",
    "512": "Álgebra",
    "513": "Aritmética",
    "514": "Topologia",
    "515": "Análise e cálculo",
    "516": "Geometria",
    "519": "Probabilidades e matemática aplicada",
    "520": "Astronomia",
    "523": "Corpos celestes específicos",
    "530": "Física",
    "531": "Mecânica clássica",
    "535": "Luz e ótica",
    "537": "Eletricidade e eletrônica",
    "539": "Física moderna",
    "540": "Química",
    "550": "Ciências da Terra e Geologia",
    "560": "Paleontologia (Fósseis)",
    "570": "Ciências da vida e Biologia",
    "572": "Bioquímica",
    "576": "Genética e evolução",
    "577": "Ecologia",
    "580": "Plantas (Botânica)",
    "590": "Animais (Zoologia)",
    "595": "Artrópodes (Insetos, Aranhas)",
    "597": "Vertebrados de sangue frio (Peixes, Répteis)",
    "598": "Aves",
    "599": "Mamíferos",

    // --- 600: TECNOLOGIA ---
    "600": "Tecnologia",
    "610": "Medicina e saúde",
    "611": "Anatomia humana",
    "612": "Fisiologia humana",
    "613": "Promoção da saúde (Higiene, Fitness)",
    "615": "Farmacologia e terapêutica",
    "616": "Doenças",
    "617": "Cirurgia",
    "618": "Ginecologia, obstetrícia, pediatria",
    "620": "Engenharia e operações afins",
    "621": "Física aplicada (Elétrica, Eletrônica, Mecânica)",
    "624": "Engenharia civil",
    "629": "Outros ramos da engenharia (Automóveis, Aeroespacial)",
    "630": "Agricultura",
    "636": "Pecuária e animais de estimação",
    "640": "Gestão doméstica e familiar",
    "641": "Comida e bebida (Culinária)",
    "650": "Gestão e serviços auxiliares",
    "657": "Contabilidade",
    "658": "Gestão geral (Administração)",
    "659": "Publicidade e relações públicas",
    "660": "Engenharia química",
    "670": "Fabricação industrial",
    "680": "Fabricação de produtos para usos específicos",
    "690": "Construção de edifícios",

    // --- 700: ARTES ---
    "700": "Artes",
    "709": "História da arte",
    "710": "Urbanismo e paisagismo",
    "720": "Arquitetura",
    "730": "Artes plásticas e escultura",
    "740": "Desenho e artes decorativas",
    "741": "Desenho e caricaturas (Quadrinhos)",
    "745": "Artes decorativas",
    "750": "Pintura",
    "760": "Artes gráficas e gravuras",
    "770": "Fotografia",
    "780": "Música",
    "781": "Teoria musical e formas gerais",
    "782": "Música vocal",
    "784": "Instrumentos e conjuntos",
    "786": "Instrumentos de teclado",
    "787": "Instrumentos de corda",
    "790": "Artes recreativas e de espetáculo",
    "791": "Espetáculos públicos (Cinema, Circo)",
    "792": "Teatro",
    "793": "Jogos e diversões de salão",
    "794": "Jogos de habilidade (Xadrez, Computador)",
    "796": "Esportes e jogos atléticos",

    // --- 800: LITERATURA ---
    "800": "Literatura e retórica",
    "810": "Literatura americana em inglês",
    "820": "Literatura inglesa",
    "830": "Literatura alemã",
    "840": "Literatura francesa",
    "850": "Literatura italiana",
    "860": "Literaturas espanhola e portuguesa",
    "869": "Literatura brasileira e portuguesa",
    "869.1": "Poesia brasileira",
    "869.2": "Teatro brasileiro",
    "869.3": "Romance e ficção brasileira",
    "869.4": "Ensaios brasileiros",
    "869.9": "Literatura portuguesa",
    "870": "Literaturas itálicas (Latina)",
    "880": "Literaturas helênicas (Grega clássica)",
    "890": "Literaturas de outras línguas",

    // --- 900: HISTÓRIA & GEOGRAFIA ---
    "900": "História e geografia",
    "910": "Geografia e viagens",
    "914": "Geografia da Europa",
    "918": "Geografia da América do Sul",
    "920": "Biografia, genealogia, insígnias",
    "930": "História do mundo antigo",
    "931": "China antiga",
    "932": "Egito antigo",
    "937": "Roma antiga",
    "938": "Grécia antiga",
    "940": "História da Europa",
    "941": "Ilhas britânicas",
    "943": "Alemanha",
    "944": "França",
    "950": "História da Ásia",
    "960": "História da África",
    "970": "História da América do Norte",
    "973": "Estados Unidos",
    "980": "História da América do Sul",
    "981": "História do Brasil",
    "981.01": "Brasil Colônia",
    "981.03": "Brasil Império",
    "981.06": "Brasil República",
    "990": "História de outras áreas"
};
