/**
 * AVISO DE PROPRIEDADE INTELECTUAL
 * * O código deste arquivo (estrutura JSON) é distribuído sob licença MIT.
 * ENTRETANTO, os valores de texto (As descrições da Classificação Decimal de Dewey)
 * são propriedade intelectual da OCLC (Online Computer Library Center).
 * * Estes dados são utilizados neste projeto estritamente para fins 
 * educacionais, de estudo pessoal e referência local (Fair Use).
 * A redistribuição comercial destes dados específicos não é autorizada 
 * pela licença MIT do restante do projeto.
 * * Fonte de referência: OCLC Dewey Summaries.
 */
const cddDatabase = {
    "000": "Generalidades e Ciência da Computação",
    "001": "Conhecimento e Teoria",
    "001.4": "Métodos de estudo, Metodologia e Pesquisa",
    "001.42": "Pesquisa científica",
    "001.94": "Mistérios e fatos misteriosos",
    "001.942": "Discos voadores, Óvnis",
    "001.944": "Monstros e temas relacionados",
    "002": "O livro",
    "003": "Sistemas",
    "004": "Processamento de dados e Ciência da Computação",
    "004.03": "Dicionário de computação",
    "004.07": "Computação – Estudo e ensino",
    "004.6": "Redes de computadores",
    "004.678": "Internet",
    "005": "Programação, software e dados",
    "005.1": "Desenvolvimento de software",
    "006": "Métodos especiais (IA, Gráficos)",
    "010": "Bibliografias",
    "011": "Bibliografias gerais",
    "012": "Bibliografias e catálogos individuais",
    "013": "Bibliografias e catálogos de autores por classes específicas",
    "014": "Bibliografias e catálogos de trabalhos anônimos ou com pseudônimos",
    "015": "Bibliografia e catálogos de trabalhos de lugares específicos",
    "016": "Bibliografia e catálogo de trabalhos de assuntos específicos",
    "016.981": "Bibliografia do Brasil",
    "017": "Catálogos de bibliotecas privadas, públicas, leilões",
    "018": "Catálogos arranjados por autor, assunto, data",
    "019": "Catálogos dicionário, Arquivos e técnicas de arquivo",
    "020": "Biblioteconomia e Ciência da Informação",
    "021": "Conexão e relacionamento entre bibliotecas, arquivos e centros",
    "022": "Administração de planta física",
    "023": "Administração de pessoal",
    "025": "Operações e rotinas de bibliotecas e documentação",
    "025.1": "Administração de bibliotecas",
    "025.2": "Aquisição e desenvolvimento da coleção",
    "025.3": "Análise bibliográfica e controle (Catalogação)",
    "025.4": "Análises de assuntos e controle (CDD, CDU)",
    "025.5": "Serviços aos usuários (Referência)",
    "030": "Enciclopédias gerais",
    "050": "Publicações seriadas e revistas",
    "060": "Organizações gerais e museologia",
    "070": "Notícias da mídia, jornalismo e editorial",
    "071": "Jornais na América do Norte",
    "072": "Jornais nas ilhas britânicas; na Inglaterra",
    "073": "Jornais na Europa central; na Alemanha",
    "074": "Jornais na França e Mônaco",
    "075": "Jornais na Itália e ilhas adjacentes",
    "076": "Jornais na Península Ibérica e ilhas adjacentes",
    "077": "Jornais na Europa oriental; na Rússia",
    "078": "Jornais na Escandinávia",
    "079": "Jornais em outras áreas geográficas",
    "080": "Coleções gerais",
    "090": "Manuscritos e livros raros",
    "100": "Filosofia e psicologia",
    "110": "Metafísica",
    "120": "Epistemologia, causalidade, gênero humano",
    "130": "Parapsicologia e ocultismo",
    "133": "Tópicos específicos em parapsicologia e ocultismo",
    "140": "Escolas filosóficas específicas",
    "150": "Psicologia",
    "152": "Percepção, movimento, emoções",
    "153": "Processos mentais e inteligência",
    "154": "Subconsciente e estados alterados",
    "155": "Psicologia diferencial e do desenvolvimento",
    "158": "Psicologia aplicada (Autoajuda)",
    "158.1": "Comportamento, Auto ajuda, Aperfeiçoamento pessoal",
    "158.125": "Meditação transcendental",
    "158.128": "Meditação",
    "160": "Lógica",
    "170": "Ética (Filosofia moral)",
    "180": "Filosofia antiga, medieval e oriental",
    "190": "Filosofia ocidental moderna",
    "200": "Religião",
    "210": "Filosofia e teoria da religião",
    "220": "Bíblia",
    "221": "Antigo Testamento",
    "225": "Novo Testamento",
    "230": "Cristianismo e teologia cristã",
    "240": "Moral cristã e teologia devocional",
    "250": "Ordens cristãs e igreja local",
    "260": "Teologia social e eclesiologia",
    "270": "História do cristianismo",
    "280": "Denominações e seitas cristãs",
    "290": "Outras religiões",
    "294": "Religiões de origem indiana (Budismo, Hinduísmo)",
    "296": "Judaísmo",
    "297": "Islamisno",
    "300": "Ciências sociais",
    "301": "Sociologia e antropologia",
    "302": "Interação social",
    "303": "Processos sociais (Guerra, Conflito)",
    "304": "Fatores que afetam o comportamento social",
    "305": "Grupos sociais (Jovens, Idosos, Mulheres)",
    "306": "Cultura e instituições",
    "310": "Coleções de estatística geral",
    "314": "Estatística geral da Europa",
    "315": "Estatística geral da Ásia",
    "316": "Estatística geral da África",
    "317": "Estatística geral da América do Norte",
    "318": "Estatística geral da América do Sul",
    "319": "Estatística geral de outras áreas",
    "320": "Ciência política",
    "327": "Relações internacionais",
    "330": "Economia",
    "331": "Economia trabalhista",
    "332": "Economia financeira",
    "333": "Economia de terra e energia",
    "334": "Cooperativas",
    "335": "Socialismo e sistemas relacionados",
    "336": "Finanças públicas",
    "337": "Economia internacional",
    "338": "Produção",
    "339": "Macroeconomia e tópicos relacionados",
    "340": "Direito",
    "341": "Direito das nações",
    "342": "Direito constitucional e administrativo",
    "343": "Direito militar, impostos, mercantil e industrial",
    "344": "Direito trabalhista, social, educacional e cultural",
    "345": "Direito criminal",
    "346": "Direito privado",
    "347": "Procedimento e tribunais cíveis",
    "348": "Leis, regulamentos e casos",
    "349": "Direiro de específicas jurisdições e áreas",
    "350": "Administração pública e ciência militar",
    "360": "Problemas e serviços sociais",
    "362": "Serviços de bem-estar social",
    "364": "Criminologia",
    "370": "Educação",
    "371": "Escolas e suas atividades; educação especial",
    "372": "Ensino Fundamental",
    "373": "Ensino Secundário",
    "374": "Ensino adulto",
    "375": "Currículos",
    "378": "Ensino Superior",
    "379": "Assuntos de politica pública na educação",
    "380": "Comércio, comunicações e transporte",
    "390": "Costumes, etiqueta e folclore",
    "400": "Linguagem",
    "410": "Linguística",
    "419": "Linguagem de sinais",
    "420": "Inglês e inglês antigo",
    "430": "Línguas germânicas (Alemão)",
    "440": "Línguas românicas (Francês)",
    "450": "Italiano, romeno",
    "460": "Espanhol e Português",
    "469": "Português",
    "470": "Línguas itálicas (Latim)",
    "480": "Línguas helênicas (Grego)",
    "490": "Outras línguas",
    "500": "Ciências naturais e matemática",
    "510": "Matemática",
    "511": "Princípios gerais da matemática",
    "512": "Álgebra",
    "513": "Aritmética",
    "514": "Topologia",
    "515": "Análise e cálculo",
    "516": "Geometria",
    "519": "Probabilidades e matemática aplicada",
    "520": "Astronomia",
    "523": "Corpos celestes específicos",
    "530": "Física",
    "531": "Mecânica clássica",
    "535": "Luz e ótica",
    "537": "Eletricidade e eletrônica",
    "539": "Física moderna",
    "540": "Química",
    "550": "Ciências da Terra e Geologia",
    "560": "Paleontologia (Fósseis)",
    "570": "Ciências da vida e Biologia",
    "572": "Bioquímica",
    "576": "Genética e evolução",
    "577": "Ecologia",
    "580": "Plantas (Botânica)",
    "590": "Animais (Zoologia)",
    "595": "Artrópodes (Insetos, Aranhas)",
    "597": "Vertebrados de sangue frio (Peixes, Répteis)",
    "598": "Aves",
    "599": "Mamíferos",
    "600": "Tecnologia",
    "610": "Medicina e saúde",
    "611": "Anatomia humana",
    "612": "Fisiologia humana",
    "613": "Promoção da saúde (Higiene, Fitness)",
    "615": "Farmacologia e terapêutica",
    "616": "Doenças",
    "617": "Cirurgia",
    "618": "Ginecologia, obstetrícia, pediatria",
    "620": "Engenharia e operações afins",
    "621": "Física aplicada (Elétrica, Eletrônica, Mecânica)",
    "624": "Engenharia civil",
    "629": "Outros ramos da engenharia (Automóveis, Aeroespacial)",
    "630": "Agricultura",
    "636": "Pecuária e animais de estimação",
    "640": "Gestão doméstica e familiar",
    "641": "Comida e bebida (Culinária)",
    "650": "Gestão e serviços auxiliares",
    "657": "Contabilidade",
    "658": "Gestão geral (Administração)",
    "659": "Publicidade e relações públicas",
    "660": "Engenharia química",
    "670": "Fabricação industrial",
    "680": "Fabricação de produtos para usos específicos",
    "690": "Construção de edifícios",
    "700": "Artes",
    "709": "História da arte",
    "710": "Urbanismo e paisagismo",
    "720": "Arquitetura",
    "730": "Artes plásticas e escultura",
    "740": "Desenho e artes decorativas",
    "741": "Desenho e caricaturas (Quadrinhos)",
    "745": "Artes decorativas",
    "750": "Pintura",
    "760": "Artes gráficas e gravuras",
    "770": "Fotografia",
    "780": "Música",
    "781": "Teoria musical e formas gerais",
    "782": "Música vocal",
    "784": "Instrumentos e conjuntos",
    "786": "Instrumentos de teclado",
    "787": "Instrumentos de corda",
    "790": "Artes recreativas e de espetáculo",
    "791": "Espetáculos públicos (Cinema, Circo)",
    "792": "Teatro",
    "793": "Jogos e diversões de salão",
    "794": "Jogos de habilidade (Xadrez, Computador)",
    "796": "Esportes e jogos atléticos",
    "800": "Literatura e retórica",
    "810": "Literatura americana em inglês",
    "820": "Literatura inglesa",
    "830": "Literatura alemã",
    "840": "Literatura francesa",
    "850": "Literatura italiana",
    "860": "Literaturas espanhola e portuguesa",
    "869": "Literatura brasileira e portuguesa",
    "869.1": "Poesia brasileira",
    "869.2": "Teatro brasileiro",
    "869.3": "Romance e ficção brasileira",
    "869.4": "Ensaios brasileiros",
    "869.9": "Literatura portuguesa",
    "870": "Literaturas itálicas (Latina)",
    "880": "Literaturas helênicas (Grega clássica)",
    "890": "Literaturas de outras línguas",
    "900": "História e geografia",
    "901": "Filosofia e teoria da história",
    "902": "Miscelânea histórica",
    "903": "Dicionários e enciclopédias históricas",
    "904": "Relatos coletivos de eventos",
    "905": "Publicações em série históricas",
    "906": "Organizações e gerenciamento",
    "907": "Educação, pesquisa e tópicos relacionados",
    "908": "Tratamento da história por classe de pessoas",
    "909": "História do mundo (Geral)",
    "910": "Geografia e viagens",
    "914": "Geografia da Europa",
    "918": "Geografia da América do Sul",
    "920": "Biografia, genealogia, insígnias",
    "928": "Biografias de escritores e personagens históricos",
    "928.1": "Escritores americanos",
    "928.69": "Escritores portugueses",
    "928.6981": "Escritores brasileiros",
    "929": "Genealogia, nomes e insígnia",
    "930": "História do mundo antigo (até ca. 499 d.C.)",
    "931": "China antiga (até 420)",
    "932": "Egito antigo (até 640)",
    "933": "Palestina (até 70)",
    "934": "Índia antiga (até 647)",
    "935": "Mesopotâmia e planalto iraniano (até 637)",
    "936": "Norte da Europa e oeste da Itália (até ca. 499)",
    "937": "Itália antiga e territórios adjacentes (até 476)",
    "938": "Grécia antiga (até 323)",
    "939": "Outras partes do mundo antigo (até 640)",
    "940": "História da Europa",
    "941": "Ilhas britânicas",
    "942": "Inglaterra e Gales",
    "943": "Europa central; Alemanha",
    "944": "França e Mônaco",
    "945": "Península itálica e ilhas adjacentes",
    "946": "Península ibérica e ilhas adjacentes",
    "947": "Europa oriental; Rússia",
    "948": "Escandinávia",
    "949": "Outras partes da Europa",
    "950": "História da Ásia; Oriente distante",
    "951": "China e áreas adjacentes",
    "952": "Japão",
    "953": "Península árabe e áreas adjacentes",
    "954": "Sul da Ásia; Índia",
    "955": "Irã",
    "956": "Oriente Médio (Oriente próximo)",
    "957": "Sibéria (Rússia asiática)",
    "958": "Ásia central",
    "959": "Sudeste da Ásia",
    "960": "História da África",
    "961": "Tunísia e Líbia",
    "962": "Egito e Sudão",
    "963": "Etiópia e Eritréia",
    "964": "Costa do noroeste da África e ilhas litorâneas",
    "965": "Algéria",
    "966": "Oeste da África e ilhas litorâneas",
    "967": "África central e ilhas litorâneas",
    "968": "África do Sul; República da África do Sul",
    "969": "Ilhas do oceano Índico-sul",
    "970": "História da América do Norte",
    "971": "Canadá",
    "972": "Mesoamérica; México",
    "973": "Estados Unidos",
    "974": "Nordeste dos Estados Unidos",
    "975": "Sudeste dos Estados Unidos",
    "976": "Centro-sul dos Estados Unidos",
    "977": "Centro-norte dos Estados Unidos",
    "978": "Oeste dos Estados Unidos",
    "979": "Região da Grande Bacia e Vertente do Pacífico",
    "980": "História da América do Sul",
    "981": "História do Brasil",
    "981.01": "Brasil Colônia",
    "981.03": "Brasil Império",
    "981.06": "Brasil República",
    "982": "Argentina",
    "983": "Chile",
    "984": "Bolívia",
    "985": "Perú",
    "986": "Colômbia e Equador",
    "987": "Venezuela",
    "988": "Guiana",
    "989": "Paraguai e Uruguai",
    "990": "História de outras áreas",
    "993": "Nova Zelândia",
    "994": "Austrália",
    "995": "Melanésia; Nova Guiné",
    "996": "Outras partes do Pacífico; Polinésia",
    "997": "Ilhas do oceano Atlântico",
    "998": "Ilhas do Ártico e Antártica",
    "999": "Mundos extraterrestres"
};
