/**
 * BASE DE DADOS CDU (Classificação Decimal Universal)
 * Estrutura: Lista Plana (Array) gerada a partir da estrutura hierárquica original.
 * Compatível com o motor de busca unificado do app.js.
 */
const baseCDU = [
    // --- TABELAS PRINCIPAIS (RAIZ) ---
    { code: "0", desc: "Ciência e conhecimento. Organização. Informática. Informação. Documentação. Biblioteconomia. Instituições. Publicações" },
    { code: "1", desc: "Filosofia. Psicologia" },
    { code: "2", desc: "Religião. Teologia" },
    { code: "3", desc: "Ciências sociais" },
    { code: "5", desc: "Matemática. Ciências naturais" },
    { code: "6", desc: "Ciências aplicadas. Medicina. Tecnologia" },
    { code: "7", desc: "Arte. Recreação. Entretenimento. Desporto" },
    { code: "8", desc: "Língua. Linguística. Literatura" },
    { code: "9", desc: "Geografia. Biografia. História" },

    // --- CLASSE 0: CIÊNCIA E CONHECIMENTO ---
    { code: "00", desc: "Prolegómenos. Fundamentos do conhecimento e da cultura. Propadéutica" },
    { code: "001", desc: "Ciência e conhecimento em geral. Organização do trabalho intelectual" },
    { code: "001.1", desc: "Conceitos da ciência e do conhecimento" },
    { code: "001.18", desc: "Futuro do conhecimento" },
    { code: "001.32", desc: "Sociedades eruditas, científicas. Academias" },
    { code: "001.8", desc: "Metodologia" },
    { code: "001.89", desc: "Organização da ciência e do trabalho científico" },
    { code: "001.9", desc: "Disseminação das ideias" },
    { code: "002", desc: "Documentação. Livros. Escritos. Autoria" },
    { code: "003", desc: "Sistemas de escrita e escritas" },
    { code: "003.01", desc: "Origens, precursores da escrita. Formas primitivas de escrita" },
    { code: "003.02", desc: "Aparecimento da escrita" },
    { code: "003.03", desc: "Expressão gráfica da linguagem" },
    { code: "003.05", desc: "Meios de produção de signos e escritas" },
    { code: "003.07", desc: "Usos e estilos da escrita" },
    { code: "003.08", desc: "Características da escrita" },
    { code: "003.09", desc: "Técnicas e métodos de decifração de escritas" },
    { code: "003.2", desc: "Sistemas de escrita. Representação gráfica de conceitos" },
    { code: "003.21", desc: "Escrita pictográfica" },
    { code: "003.22", desc: "Sistemas de escrita silábicos" },
    { code: "003.23", desc: "Sistemas de escrita alfabéticos. Ortografias" },
    { code: "003.3", desc: "Escritas" },
    { code: "003.5", desc: "Materiais e equipamentos de escrita" },
    { code: "003.6", desc: "Outros tipos de representação gráfica do pensamento" },
    { code: "004", desc: "Ciência e tecnologia informáticas. Computação. Processamento de dados" },
    { code: "004.01", desc: "Documentação" },
    { code: "004.02", desc: "Métodos de resolução dos problemas" },
    { code: "004.03", desc: "Tipos e características dos sistemas" },
    { code: "004.04", desc: "Orientação do processamento" },
    { code: "004.05", desc: "Qualidade dos sistemas e do software" },
    { code: "004.07", desc: "Características da memória" },
    { code: "004.08", desc: "Dispositivos de entrada (input), saída (output) e armazenamento" },
    { code: "004.2", desc: "Arquitectura dos computadores" },
    { code: "004.22", desc: "Representação dos dados" },
    { code: "004.23", desc: "Arquitectura de conjunto de instruções" },
    { code: "004.25", desc: "Sistemas de memória" },
    { code: "004.27", desc: "Arquitecturas avançadas. Outras arquitecturas que a de Von Neumann" },
    { code: "004.3", desc: "Hardware. Equipamento informático" },
    { code: "004.31", desc: "Unidades de processamento. Circuitos de processamento" },
    { code: "004.32", desc: "Circuitos do computador" },
    { code: "004.33", desc: "Unidades da memória. Unidades de armazenamento" },
    { code: "004.35", desc: "Periféricos. Unidades de entrada e saída (input-output)" },
    { code: "004.38", desc: "Computador. Tipos de computador" },
    { code: "004.4", desc: "Software. Programas de computador" },
    { code: "004.41", desc: "Engenharia de software" },
    { code: "004.42", desc: "Programação de computadores" },
    { code: "004.43", desc: "Linguagens de computador" },
    { code: "004.45", desc: "Programas de sistemas" },
    { code: "004.49", desc: "Infecções de computador" },
    { code: "004.5", desc: "Interacção homem-computador. Interface homem-máquina" },
    { code: "004.51", desc: "Interface de exibição" },
    { code: "004.52", desc: "Interface de som" },
    { code: "004.55", desc: "Hipermédia. Hipertexto" },
    { code: "004.58", desc: "Ajuda ao utilizador" },
    { code: "004.6", desc: "Dados" },
    { code: "004.62", desc: "Tratamento de dados" },
    { code: "004.63", desc: "Ficheiros" },
    { code: "004.65", desc: "Bases de dados e suas estruturas" },
    { code: "004.67", desc: "Sistemas para dados numéricos" },
    { code: "004.7", desc: "Comunicação de computadores. Redes de computadores" },
    { code: "004.71", desc: "Equipamento para comunicação entre computadores" },
    { code: "004.72", desc: "Arquitectura de redes" },
    { code: "004.73", desc: "Redes de acordo com a área coberta" },
    { code: "004.738", desc: "Interconexão de redes" },
    { code: "004.75", desc: "Sistemas de processamento distribuído" },
    { code: "004.77", desc: "Aplicações e serviços gerais de rede" },
    { code: "004.78", desc: "Sistemas de computadores em linha para fins específicos" },
    { code: "004.8", desc: "Inteligência artificial" },
    { code: "004.9", desc: "Técnicas baseadas em computadores e orientadas para aplicações" },
    { code: "004.91", desc: "Processamento e produção do documento" },
    { code: "004.92", desc: "Infografia. Computação gráfica" },
    { code: "004.93", desc: "Processamento de padrões de informação" },
    { code: "004.94", desc: "Simulação" },
    { code: "005", desc: "Gestão" },
    { code: "005.1", desc: "Teoria da gestão" },
    { code: "005.2", desc: "Agentes da gestão. Mecanismos. Medidas" },
    { code: "005.3", desc: "Actividades de gestão" },
    { code: "005.31", desc: "Investigação operacional (IO)" },
    { code: "005.32", desc: "Comportamento organizacional. Psicologia da gestão" },
    { code: "005.33", desc: "Factores condicionantes da gestão" },
    { code: "005.4", desc: "Processos na gestão" },
    { code: "005.5", desc: "Operações de gestão. Direcção" },
    { code: "005.6", desc: "Gestão da qualidade. Gestão da qualidade total (TQM)" },
    { code: "005.7", desc: "Gestão da organização" },
    { code: "005.9", desc: "Áreas, campos da gestão" },
    { code: "005.91", desc: "Gestão administrativa. Secretariado" },
    { code: "005.92", desc: "Gestão de documentos de arquivo" },
    { code: "005.93", desc: "Gestão das instalações. Gestão dos recursos físicos" },
    { code: "005.94", desc: "Gestão de conhecimentos" },
    { code: "005.95", desc: "Gestão de pessoal. Gestão de recursos humanos" },
    { code: "006", desc: "Normalização de produtos, operações, pesos, medidas e tempo" },
    { code: "006.91", desc: "Metrologia. Pesos e medidas em geral" },
    { code: "006.92", desc: "Horologia. Determinação e normalização do tempo" },
    { code: "007", desc: "Actividade e organização. Teoria da comunicação e do controlo (cibernética)" },
    { code: "007.5", desc: "Sistemas automáticos" },
    { code: "008", desc: "Civilização. Cultura. Progresso" },
    { code: "01", desc: "Bibliografia e bibliografias. Catálogos" },
    { code: "011", desc: "Bibliografias universais e gerais" },
    { code: "012", desc: "Bibliografias de autores. Bibliografias individuais" },
    { code: "013", desc: "Bibliografias colectivas" },
    { code: "014", desc: "Bibliografias de obras com características especiais" },
    { code: "015", desc: "Bibliografias segundo o lugar" },
    { code: "016", desc: "Bibliografias de assuntos específicos" },
    { code: "017", desc: "Catálogos em geral. Catálogos de assunto" },
    { code: "018", desc: "Catálogos onomásticos" },
    { code: "019", desc: "Catálogos-dicionários" },
    { code: "02", desc: "Biblioteconomia" },
    { code: "021", desc: "Função, valor, utilidade, criação, desenvolvimento de bibliotecas" },
    { code: "022", desc: "Localização da biblioteca, edifícios. Equipamento" },
    { code: "023", desc: "Administração da biblioteca. Pessoal" },
    { code: "024", desc: "Relações da biblioteca com o público. Regulamentos" },
    { code: "025", desc: "Departamentos administrativos das bibliotecas" },
    { code: "026", desc: "Bibliotecas especializadas" },
    { code: "027", desc: "Bibliotecas gerais" },
    { code: "027.6", desc: "Bibliotecas destinadas a determinadas categorias de leitores" },
    { code: "027.7", desc: "Bibliotecas de estabelecimentos de ensino superior" },
    { code: "027.8", desc: "Bibliotecas de estabelecimentos de ensino primário e secundário" },
    { code: "030", desc: "Obras gerais de referência" },
    { code: "050", desc: "Publicações periódicas, periódicos" },
    { code: "06", desc: "Organizações em geral" },
    { code: "06.01", desc: "Direitos e deveres dos membros" },
    { code: "06.05", desc: "Recompensas. Distinções. Prémios" },
    { code: "061", desc: "Organizações e outros tipos de cooperação" },
    { code: "061.1", desc: "Organizações e cooperação governamentais" },
    { code: "061.2", desc: "Organizações e cooperação não governamentais" },
    { code: "061.23", desc: "Organizações com fins humanitários, filantrópicos" },
    { code: "061.25", desc: "Organizações e movimentos secretos e semi-secretos" },
    { code: "061.27", desc: "Fundações. Dotações. Institutos" },
    { code: "069", desc: "Museus. Exposições permanentes" },
    { code: "070", desc: "Jornais. Imprensa" },
    { code: "08", desc: "Poligrafias. Obras de autoria colectiva" },
    { code: "082", desc: "Poligrafias colectivas" },
    { code: "084", desc: "Material pictórico" },
    { code: "086", desc: "Documentos de forma particular" },
    { code: "087", desc: "Documentos de origem ou destino particular" },
    { code: "09", desc: "Manuscritos. Obras raras e notáveis" },
    { code: "091", desc: "Manuscritos" },
    { code: "092", desc: "Livros xilográficos" },
    { code: "093", desc: "Incunábulos" },
    { code: "094", desc: "Outras obras impressas notáveis e raras" },
    { code: "095", desc: "Obras notáveis pela encadernação" },
    { code: "096", desc: "Obras notáveis pelas ilustrações" },
    { code: "097", desc: "Marcas de propriedade ou de origem" },

    // --- CLASSE 1: FILOSOFIA. PSICOLOGIA ---
    { code: "101", desc: "Natureza e âmbito da filosofia" },
    { code: "11", desc: "Metafísica" },
    { code: "111", desc: "Metafísica geral. Ontologia" },
    { code: "113", desc: "Cosmologia. Filosofia da natureza" },
    { code: "122", desc: "Metafísica especial" },
    { code: "13", desc: "Filosofia da mente e do espírito" },
    { code: "130.1", desc: "Conceitos e leis gerais" },
    { code: "130.2", desc: "Filosofia da cultura. Sistemas culturais" },
    { code: "130.3", desc: "Metafísica da vida espiritual" },
    { code: "133", desc: "Paranormal. O oculto. Fenómenos psi" },
    { code: "14", desc: "Sistemas e pontos de vista filosóficos" },
    { code: "140", desc: "Atitudes filosóficas possíveis. Tipologia" },
    { code: "141", desc: "Tipos de pontos de vista filosóficos" },
    { code: "159.9", desc: "Psicologia" },
    { code: "159.91", desc: "Psicofisiologia. Fisiologia mental" },
    { code: "159.92", desc: "Desenvolvimento e capacidade mental. Psicologia comparada" },
    { code: "159.93", desc: "Sensação. Percepção sensorial" },
    { code: "159.94", desc: "Funções executivas" },
    { code: "159.942", desc: "Emoções. Afectos. Sensibilidade" },
    { code: "159.943", desc: "Conação e movimento" },
    { code: "159.944", desc: "Trabalho e fadiga. Eficiência" },
    { code: "159.946", desc: "Funções motoras especiais" },
    { code: "159.947", desc: "Vontade" },
    { code: "159.95", desc: "Processos mentais superiores" },
    { code: "159.96", desc: "Estados e processos mentais especiais" },
    { code: "159.97", desc: "Psicopatologia" },
    { code: "159.98", desc: "Psicologia aplicada" },
    { code: "16", desc: "Lógica. Epistemologia. Teoria do conhecimento" },
    { code: "161", desc: "Fundamentos da lógica" },
    { code: "164", desc: "Logística. Lógica simbólica. Cálculo lógico" },
    { code: "165", desc: "Teoria do conhecimento. Epistemologia" },
    { code: "165.6", desc: "Pontos de vista e doutrinas epistemológicas" },
    { code: "167", desc: "Metodologia lógica" },
    { code: "17", desc: "Filosofia moral. Ética. Filosofia prática" },
    { code: "171", desc: "Ética individual. Deveres para consigo mesmo" },
    { code: "172", desc: "Ética social. Deveres para com os outros" },
    { code: "173", desc: "Ética familiar" },
    { code: "176", desc: "Ética sexual. Moralidade sexual" },
    { code: "177", desc: "Ética e sociedade" },

    // --- CLASSE 2: RELIGIÃO. TEOLOGIA ---
    { code: "2-1", desc: "Teoria e filosofia da religião. Natureza da religião" },
    { code: "2-13", desc: "O divino. O Sagrado. O Sobrenatural" },
    { code: "2-14", desc: "Deus. Deuses" },
    { code: "2-15", desc: "Natureza de Deus" },
    { code: "2-17", desc: "Universo. Natureza do Universo. Cosmologia" },
    { code: "2-18", desc: "Homem. Humanidade. Condição humana" },
    { code: "2-184", desc: "Relação do Homem com Deus" },
    { code: "2-2", desc: "Provas da religião" },
    { code: "2-23", desc: "Livros sagrados. Escrituras. Textos religiosos" },
    { code: "2-25", desc: "Literatura secundária. Obras pseudocanónicas" },
    { code: "2-27", desc: "Obras críticas" },
    { code: "2-28", desc: "Outros textos religiosos" },
    { code: "2-3", desc: "Pessoas na religião" },
    { code: "2-31", desc: "Criador, fundador, figura central da fé" },
    { code: "2-32", desc: "Messias" },
    { code: "2-34", desc: "Mártires" },
    { code: "2-35", desc: "Ascetas. Eremitas. Faquires" },
    { code: "2-36", desc: "Santos. Bodhisattvas. Pessoas iluminadas" },
    { code: "2-37", desc: "Mahatmas. Gurus. Sábios" },
    { code: "2-38", desc: "Carismáticos. Pessoas com poderes sobrenaturais" },
    { code: "2-4", desc: "Actividades religiosas. Práticas religiosas" },
    { code: "2-42", desc: "Comportamento moral. Teologia moral" },
    { code: "2-43", desc: "Costumes e prática social. Teologia social" },
    { code: "2-46", desc: "Caridade. Apoio aos outros. Actividades pastorais" },
    { code: "2-47", desc: "Educação religiosa" },
    { code: "2-475", desc: "Pregação. Homiliética" },
    { code: "2-5", desc: "Veneração. Culto. Rituais e cerimónias" },
    { code: "2-523", desc: "Edifícios para uso religioso. Eclesiologia" },
    { code: "2-526", desc: "Objectos do culto. Mobiliário e decoração" },
    { code: "2-53", desc: "Actos de veneração/adoração" },
    { code: "2-54", desc: "Cerimónias segundo o objectivo" },
    { code: "2-55", desc: "Sacramentos" },
    { code: "2-56", desc: "Celebração" },
    { code: "2-6", desc: "Processos em religião" },
    { code: "2-65", desc: "Comparação de religiões" },
    { code: "2-67", desc: "Relações entre confissões religiosas ou com a sociedade" },
    { code: "2-7", desc: "Organização e administração religiosa" },
    { code: "2-72", desc: "Natureza e estructura da religião organizada. Eclesiologia" },
    { code: "2-73", desc: "Governo da religião" },
    { code: "2-74", desc: "Administração legal. Lei religiosa. Direito canónico" },
    { code: "2-76", desc: "Recrutamento. Actividade missionária. Missiologia" },
    { code: "2-77", desc: "Estrutura organizacional da fé, da religião" },
    { code: "2-78", desc: "Organizações religiosas. Sociedades e associações religiosas" },
    { code: "2-8", desc: "Religiões segundo as suas características" },
    { code: "2-84", desc: "Religiões associadas ao Estado" },
    { code: "2-87", desc: "Cismas. Heresias" },
    { code: "2-9", desc: "História da fé, religião, denominação ou igreja" },
    { code: "21", desc: "Religiões pré-históricas e primitivas" },
    { code: "212", desc: "Religiões pré-históricas" },
    { code: "213", desc: "Religiões primitivas" },
    { code: "22", desc: "Religiões originárias do Extremo Oriente" },
    { code: "221", desc: "Religiões da China" },
    { code: "221.3", desc: "Taoismo" },
    { code: "223", desc: "Religiões da Coreia" },
    { code: "225", desc: "Religiões do Japão" },
    { code: "23", desc: "Religiões originárias do sub-continente indiano. Hinduísmo" },
    { code: "233", desc: "Hinduismo em sentido restrito" },
    { code: "234", desc: "Jainismo" },
    { code: "235", desc: "Sikhismo" },
    { code: "24", desc: "Budismo" },
    { code: "241", desc: "Budismo hinayana. O Pequeno Veículo" },
    { code: "242", desc: "Budismo mahayana. O Grande Veículo" },
    { code: "243", desc: "Lamaísmo" },
    { code: "244", desc: "Budismo japonês" },
    { code: "25", desc: "Religiões da antiguidade. Cultos e religiões menores" },
    { code: "251", desc: "Religião do Egipto antigo" },
    { code: "252", desc: "Religiões da Mesopotâmia" },
    { code: "254", desc: "Religiões do Irão" },
    { code: "255", desc: "Religiões da antiguidade clássica" },
    { code: "257", desc: "Religiões da Europa" },
    { code: "258", desc: "Religiões da América Central e do Sul. Religiões indígenas" },
    { code: "26", desc: "Judaísmo" },
    { code: "261", desc: "Religião do período Bíblico. Antigo Testamento" },
    { code: "262", desc: "Judaísmo asquenazita" },
    { code: "264", desc: "Judaísmo sefardita" },
    { code: "265", desc: "Judaísmo ortodoxo" },
    { code: "266", desc: "Judaísmo progressista" },
    { code: "267", desc: "Movimentos modernos originários do Judaísmo" },
    { code: "27", desc: "Cristianismo. Igrejas e denominações cristãs" },
    { code: "271", desc: "Igrejas do Oriente" },
    { code: "272", desc: "Igreja Católica Romana" },
    { code: "273", desc: "Igrejas episcopais católicas não filiadas a Roma" },
    { code: "274", desc: "Protestantismo em sentido lato. Puritanos" },
    { code: "275", desc: "Igrejas reformadas" },
    { code: "276", desc: "Anabaptistas" },
    { code: "277", desc: "Igrejas livres. Não conformistas" },
    { code: "278", desc: "Outras igrejas protestantes" },
    { code: "279", desc: "Outros movimentos e igrejas cristãs" },
    { code: "28", desc: "Islamismo" },
    { code: "281", desc: "Sufismo" },
    { code: "282", desc: "Islamismo sunita" },
    { code: "284", desc: "Shi'a. Islamismo xiita" },
    { code: "285", desc: "Babismo" },
    { code: "286", desc: "Bahaísmo" },
    { code: "29", desc: "Movimentos espirituais modernos" },

    // --- CLASSE 3: CIÊNCIAS SOCIAIS ---
    { code: "303", desc: "Métodos das ciências sociais" },
    { code: "304", desc: "Questões sociais. Prática social. Modo de vida" },
    { code: "305", desc: "Estudos do género" },
    { code: "308", desc: "Sociografia. Estudos descritivos da sociedade" },
    { code: "311", desc: "Estatística como ciência. Teoria estatística" },
    { code: "311.1", desc: "Fundamentos, bases da estatística" },
    { code: "311.2", desc: "Técnica de pesquisa. Preparação. Tabulação" },
    { code: "311.3", desc: "Organização geral das estatísticas. Estatísticas oficiais" },
    { code: "311.4", desc: "Estatísticas privadas" },
    { code: "314", desc: "Demografia. Estudos da população" },
    { code: "314.1", desc: "População" },
    { code: "316", desc: "Sociologia" },
    { code: "316.1", desc: "Objecto e âmbito da sociologia" },
    { code: "316.2", desc: "Pontos de vista e tendências sociológicas" },
    { code: "316.3", desc: "Estrutura social. Sociedade como sistema social" },
    { code: "316.33", desc: "Subsistemas das sociedades globais como categorias sociológicas" },
    { code: "316.34", desc: "Estratificação social. Diferenciação social" },
    { code: "316.35", desc: "Grupos sociais. Organizações sociais" },
    { code: "316.36", desc: "Casamento e familía" },
    { code: "316.4", desc: "Processos sociais. Dinâmicas sociais" },
    { code: "316.6", desc: "Psicologia social" },
    { code: "316.7", desc: "Sociologia da cultura. Contexto cultural da vida social" },
    { code: "32", desc: "Política" },
    { code: "321", desc: "Formas de organização política. Estados como poderes políticos" },
    { code: "322", desc: "Relações entre estado e igreja. Política da Igreja" },
    { code: "323", desc: "Assuntos internos. Política interna" },
    { code: "323.1", desc: "Movimentos nacionalistas, populares e étnicos. Minorias" },
    { code: "323.2", desc: "Relações entre a população e o Estado" },
    { code: "323.4", desc: "Luta de classes. Formas da luta de classes" },
    { code: "324", desc: "Eleições. Campanhas eleitorais. Resultados eleitorais" },
    { code: "325", desc: "Abertura de territórios. Colonização. Colonialismo" },
    { code: "326", desc: "Escravatura" },
    { code: "327", desc: "Relações internacionais. Política mundial. Política externa" },
    { code: "327.2", desc: "Imperialismo. Expansionismo político" },
    { code: "327.3", desc: "Internacionalismo. Movimentos internacionais" },
    { code: "327.5", desc: "Blocos internacionais" },
    { code: "327.7", desc: "Actividade das organizações internacionais" },
    { code: "327.8", desc: "Influência política, pressão sobre outros Estados" },
    { code: "328", desc: "Parlamentos. Governos" },
    { code: "329", desc: "Partidos e movimentos políticos" },
    { code: "33", desc: "Economia. Ciência económica" },
    { code: "330", desc: "Economia em geral" },
    { code: "330.1", desc: "Teoria, conceitos económicos básicos. Valor. Capital" },
    { code: "330.3", desc: "Dinâmica da economia. Movimento económico" },
    { code: "330.4", desc: "Economia matemática" },
    { code: "330.5", desc: "Propriedade nacional. Contabilidade nacional. Produto social" },
    { code: "330.8", desc: "História das teorias e doutrinas económicas" },
    { code: "331", desc: "Trabalho. Emprego. Organização do trabalho" },
    { code: "331.1", desc: "Teoria e organização do trabalho" },
    { code: "331.2", desc: "Salários. Ordenados. Pagamento" },
    { code: "331.3", desc: "Outras condições de trabalho" },
    { code: "331.4", desc: "Ambiente de trabalho. Segurança e higiene. Acidentes" },
    { code: "331.5", desc: "Mercado de trabalho. Emprego" },
    { code: "332", desc: "Economia regional. Economia territorial" },
    { code: "332.1", desc: "Economia regional" },
    { code: "332.2", desc: "Economia da terra" },
    { code: "332.3", desc: "Utilização da terra" },
    { code: "332.5", desc: "Procura da terra. Planeamento a longo prazo" },
    { code: "332.6", desc: "Valor da terra. Propriedade imóvel" },
    { code: "332.7", desc: "Comércio de terra, de bens imóveis" },
    { code: "332.8", desc: "Economia da habitação" },
    { code: "334", desc: "Formas de organização e cooperação na economia" },
    { code: "336", desc: "Finanças" },
    { code: "336.1", desc: "Finanças públicas. Finanças do governo" },
    { code: "336.2", desc: "Receitas públicas" },
    { code: "336.5", desc: "Despesa pública. Despesa do estado" },
    { code: "336.7", desc: "Moeda. Sistema monetário. Banca. Bolsa de valores" },
    { code: "338", desc: "Situação económica. Política económica. Planeamento" },
    { code: "338.1", desc: "Ciclo económico. Estrutura económica. Crescimento" },
    { code: "338.2", desc: "Controlo da economia. Gestão. Planeamento" },
    { code: "338.3", desc: "Produção" },
    { code: "338.4", desc: "Produção e serviços segundo os sectores económicos" },
    { code: "338.48", desc: "Turismo" },
    { code: "338.5", desc: "Preços. Formação de preços. Custos" },
    { code: "339", desc: "Comércio. Relações internacionais. Mercado" },
    { code: "339.3", desc: "Comércio interno. Comércio nacional" },
    { code: "339.5", desc: "Comércio externo. Comércio internacional" },
    { code: "339.7", desc: "Finanças internacionais" },
    { code: "339.9", desc: "Economia internacional. Economia global" },
    { code: "34", desc: "Direito. Jurisprudência" },
    { code: "340", desc: "Lei em geral. Métodos jurídicos" },
    { code: "340.1", desc: "Tipos e formas do direito" },
    { code: "340.13", desc: "Direito positivo. Norma legal. Estatuto" },
    { code: "340.14", desc: "Leis não escritas. Outras fontes do direito" },
    { code: "340.5", desc: "Direito comparado" },
    { code: "340.6", desc: "Ciências auxiliares. Medicina legal" },
    { code: "341", desc: "Direito internacional" },
    { code: "341.1", desc: "Direito das organizações internacionais" },
    { code: "341.2", desc: "Sujeitos e objectos do direito internacional" },
    { code: "341.3", desc: "Direito de guerra" },
    { code: "341.4", desc: "Direito penal internacional" },
    { code: "341.6", desc: "Arbitragem internacional" },
    { code: "341.7", desc: "Direito diplomático. Leis da diplomacia" },
    { code: "341.8", desc: "Direito consular" },
    { code: "341.9", desc: "Direito internacional privado. Conflitos de leis" },
    { code: "342", desc: "Direito público. Direito constitucional. Direito administrativo" },
    { code: "342.1", desc: "Estado. Povo. Nação. Poder do Estado" },
    { code: "342.2", desc: "Estado. Estrutura dos estados" },
    { code: "342.3", desc: "Autoridade suprema. Formas de Estado" },
    { code: "342.4", desc: "Constituições" },
    { code: "342.5", desc: "Poderes do Estado. Sistema e função do governo" },
    { code: "342.6", desc: "Poder executivo. Órgãos centrais do governo" },
    { code: "342.7", desc: "Direitos humanos. Direitos e deveres do cidadão" },
    { code: "342.8", desc: "Lei eleitoral. Sistemas eleitorais" },
    { code: "342.9", desc: "Direito administrativo" },
    { code: "343", desc: "Direito penal. Delitos penais" },
    { code: "343.1", desc: "Justiça penal. Processo penal" },
    { code: "343.2", desc: "Direito penal propriamente dito" },
    { code: "343.3", desc: "Delitos específicos. Crimes contra o Estado" },
    { code: "343.4", desc: "Atentados contra as liberdades fundamentais" },
    { code: "343.5", desc: "Infracções contra a confiança pública, a moral, a família" },
    { code: "343.6", desc: "Infracções contra pessoas" },
    { code: "343.8", desc: "Pena. Execução de sentença. Prevenção do crime" },
    { code: "343.9", desc: "Criminologia. Ciências criminais. Criminalística" },
    { code: "344", desc: "Direito penal militar, naval e aéreo" },
    { code: "346", desc: "Direito económico. Direito do contolo governamental" },
    { code: "346.2", desc: "Sujeitos do direito económico" },
    { code: "346.3", desc: "Contratos económicos" },
    { code: "346.5", desc: "Regulação da ordem económica e seu controlo" },
    { code: "346.6", desc: "Regulação de preços, finanças e créditos" },
    { code: "346.7", desc: "Regulação dos sectores individuais" },
    { code: "346.9", desc: "Aplicação do direito económico. Sanções" },
    { code: "347", desc: "Direito civil" },
    { code: "347.1", desc: "Direito civil em geral" },
    { code: "347.2", desc: "Direitos reais. Direitos sobre as coisas e os bens" },
    { code: "347.3", desc: "Bens móveis em geral" },
    { code: "347.4", desc: "Obrigações. Contractos. Acordos" },
    { code: "347.5", desc: "Responsabilidades não contratuais. Danos" },
    { code: "347.6", desc: "Direito da família e das sucessões" },
    { code: "347.7", desc: "Direito comercial. Direito das sociedades" },
    { code: "347.8", desc: "Direito do ar, do espaço, do éter" },
    { code: "347.9", desc: "Direito processual. Organização judiciária" },
    { code: "348", desc: "Direito eclesiástico. Direito canónico" },
    { code: "349", desc: "Ramos especiais do direito" },
    { code: "35", desc: "Administração pública. Governo. Assuntos militares" },
    { code: "351", desc: "Actividades específicas da administração pública" },
    { code: "352", desc: "Governo local. Administração municipal" },
    { code: "353", desc: "Governo regional e provincial" },
    { code: "353.1", desc: "Regiões. Estados de uma federação" },
    { code: "353.2", desc: "Províncias. Departamentos. Condados" },
    { code: "353.5", desc: "Subprefeituras. Distritos" },
    { code: "353.8", desc: "Tipos especiais da administração regional" },
    { code: "353.9", desc: "Administração independente das regiões. Ministérios" },
    { code: "354", desc: "Governo central. Nacional" },
    { code: "354.1", desc: "Ministérios para assuntos gerais" },
    { code: "355", desc: "Assuntos militares. Arte da guerra. Defesa" },
    { code: "355.1", desc: "Forças armadas. Vida militar" },
    { code: "355.2", desc: "Recrutamento. Potencial de guerra" },
    { code: "355.3", desc: "Organização geral das forças armadas" },
    { code: "355.4", desc: "Operações de guerra. Táctica. Estratégia" },
    { code: "355.5", desc: "Treino de tropas e oficiais. Exercícios tácticos" },
    { code: "355.6", desc: "Administração militar" },
    { code: "355.7", desc: "Estabelecimentos militares" },
    { code: "356", desc: "Serviços do exército. Infantaria. Soldados" },
    { code: "357", desc: "Cavalaria. Tropas motorizadas" },
    { code: "358", desc: "Artilharia. Engenharia. Aviação" },
    { code: "358.1", desc: "Artilharia" },
    { code: "358.4", desc: "Aviação militar. Força aérea" },
    { code: "359", desc: "Marinha: pessoal e organização" },
    { code: "36", desc: "Bem-estar social. Segurança social. Seguros" },
    { code: "364", desc: "Bem-estar social" },
    { code: "364-1", desc: "Teorias sobre o bem-estar social" },
    { code: "364-2", desc: "Princípios da assistência" },
    { code: "364-3", desc: "Organizações de bem-estar social" },
    { code: "364-4", desc: "Pessoas como provedoras de assistência" },
    { code: "364-5", desc: "Instalações do bem-estar social" },
    { code: "364-6", desc: "Contribuições e pagamentos" },
    { code: "364-7", desc: "Processos do bem-estar social. Serviços sociais" },
    { code: "364.2", desc: "Necessidades humanas básicas" },
    { code: "364.3", desc: "Benefícios sociais. Segurança social" },
    { code: "364.4", desc: "Áreas de actuação do serviço social" },
    { code: "364.6", desc: "Questões do bem-estar social" },
    { code: "365", desc: "Desejo de habitação. Segurança da habitação" },
    { code: "366", desc: "Consumerismo" },
    { code: "368", desc: "Seguros" },
    { code: "37", desc: "Educação" },
    { code: "37.01", desc: "Fundamentos da educação. Teoria. Política" },
    { code: "37.02", desc: "Didáctica e método" },
    { code: "37.04", desc: "Orientação" },
    { code: "37.06", desc: "Problemas sociais na educação" },
    { code: "37.07", desc: "Gestão de instituições de ensino" },
    { code: "37.09", desc: "Organização da instrução" },
    { code: "373", desc: "Tipos de escolas que ministram ensino em geral" },
    { code: "374", desc: "Ensino extra-escolar. Formação contínua" },
    { code: "376", desc: "Escolas especiais" },
    { code: "377", desc: "Formação técnica e profissional" },
    { code: "378", desc: "Ensino superior. Universidades" },
    { code: "379.8", desc: "Lazer" },
    { code: "39", desc: "Antropologia cultural. Etnologia. Usos e costumes. Folclore" },
    { code: "391", desc: "Vestuário. Moda. Adornos" },
    { code: "392", desc: "Usos e costumes na vida privada" },
    { code: "393", desc: "Morte. Funerais. Ritos mortuários" },
    { code: "394", desc: "Vida pública. Vida social" },
    { code: "395", desc: "Cerimonial social. Etiqueta. Títulos" },
    { code: "398", desc: "Folclore em sentido restrito" },

    // --- CLASSE 5: MATEMÁTICA. CIÊNCIAS NATURAIS ---
    { code: "502", desc: "Ciência ambiental. Conservação. Meio ambiente" },
    { code: "504", desc: "Ameaças ao ambiente" },
    { code: "51", desc: "Matemática" },
    { code: "510", desc: "Fundamentos das matemáticas" },
    { code: "510.2", desc: "Problemas gerais da lógica matemática" },
    { code: "510.3", desc: "Teoria dos conjuntos" },
    { code: "510.6", desc: "Lógica matemática" },
    { code: "511", desc: "Teoria dos números" },
    { code: "512", desc: "Álgebra" },
    { code: "514", desc: "Geometria" },
    { code: "514.7", desc: "Geometria diferencial. Métodos algébricos" },
    { code: "515.1", desc: "Topologia" },
    { code: "517", desc: "Análise matemática" },
    { code: "517.9", desc: "Equações diferenciais. Cálculo de variações" },
    { code: "519.1", desc: "Análise combinatória. Teoria dos grafos" },
    { code: "519.2", desc: "Probabilidade. Estatística matemática" },
    { code: "519.6", desc: "Matemática computacional. Análise numérica" },
    { code: "519.7", desc: "Cibernética matemática" },
    { code: "519.8", desc: "Investigação operacional matemática" },
    { code: "519.83", desc: "Teoria dos jogos" },
    { code: "519.85", desc: "Programação matemática" },
    { code: "52", desc: "Astronomia. Astrofísica. Geodésia" },
    { code: "520", desc: "Instrumentos e técnicas astronómicas" },
    { code: "521", desc: "Astronomia teórica. Mecânica celeste" },
    { code: "521.9", desc: "Astrometria. Astronomia esférica" },
    { code: "523", desc: "O sistema solar" },
    { code: "523.3", desc: "Sistema Terra-Lua" },
    { code: "523.4", desc: "Planetas e seus satélites. Planetologia" },
    { code: "523.6", desc: "Cometas. Meteoros. Meteoritos" },
    { code: "523.9", desc: "O Sol. Física solar" },
    { code: "524", desc: "Estrelas. Sistemas estelares. O Universo" },
    { code: "524.1", desc: "Raios cósmicos primários" },
    { code: "524.3", desc: "Estrelas" },
    { code: "524.4", desc: "Aglomerados e associações de estrelas" },
    { code: "524.5", desc: "Meio interestelar. Nebulosas galácticas" },
    { code: "524.6", desc: "A Galáxia (Via Láctea)" },
    { code: "524.7", desc: "Sistemas extragalácticos" },
    { code: "524.8", desc: "Cosmologia" },
    { code: "528", desc: "Geodésia. Levantamento. Fotogrametria. Cartografia" },
    { code: "528.1", desc: "Teoria dos erros e da correcção" },
    { code: "528.2", desc: "Forma da Terra. Geodésia matemática e física" },
    { code: "528.3", desc: "Levantamento geodésico" },
    { code: "528.4", desc: "Levantamentos de campo. Topografia" },
    { code: "528.5", desc: "Instrumentos e equipamentos geodésicos" },
    { code: "528.7", desc: "Fotogrametria: aérea, terrestre" },
    { code: "528.8", desc: "Captação remota de dados" },
    { code: "528.9", desc: "Elaboração de mapas" },
    { code: "53", desc: "Física" },
    { code: "53.01", desc: "Teoria e natureza dos fenómenos" },
    { code: "53.08", desc: "Princípios gerais e teoria da medição" },
    { code: "531", desc: "Mecânica em geral. Mecânica dos corpos sólidos" },
    { code: "531.1", desc: "Cinemática. Geometria do movimento" },
    { code: "531.2", desc: "Estática. Forças. Equilíbrio" },
    { code: "531.3", desc: "Dinâmica. Cinética" },
    { code: "531.4", desc: "Trabalho. Fricção. Resistência passiva" },
    { code: "531.5", desc: "Gravidade. Gravitação. Balística" },
    { code: "531.6", desc: "Energia mecânica. Conservação da energia" },
    { code: "531.7", desc: "Medição de quantidades geométricas e mecânicas" },
    { code: "531.8", desc: "Teoria das máquinas. Mecânica técnica" },
    { code: "532", desc: "Mecânica dos fluídos. Mecânica dos líquidos" },
    { code: "532.1", desc: "Hidrostática em geral" },
    { code: "532.6", desc: "Fenómenos de superfície. Capilaridade" },
    { code: "532.7", desc: "Teoria cinética dos líquidos. Osmose. Soluções" },
    { code: "533", desc: "Mecânica dos gases. Física do plasma" },
    { code: "533.1", desc: "Propriedades dos gases" },
    { code: "533.2", desc: "Elasticidade. Compressibilidade. Misturas" },
    { code: "533.5", desc: "Gases rarefeitos. Física do vácuo" },
    { code: "533.6", desc: "Aerodinâmica" },
    { code: "533.7", desc: "Teoria cinética dos gases" },
    { code: "533.9", desc: "Física do plasma" },
    { code: "534", desc: "Vibrações. Ondas. Acústica" },
    { code: "534.1", desc: "Vibração de corpos. Vibrações forçadas" },
    { code: "534.2", desc: "Propagação das vibrações" },
    { code: "534.3", desc: "Sons e percepção musical" },
    { code: "534.6", desc: "Medições acústicas" },
    { code: "534.7", desc: "Acústica fisiológica e médica" },
    { code: "534.8", desc: "Aplicações da acústica" },
    { code: "535", desc: "Óptica" },
    { code: "535.1", desc: "Teoria da luz" },
    { code: "535.2", desc: "Propagação e energética. Fotometria" },
    { code: "535.3", desc: "Propagação. Reflexão. Refracção. Absorção" },
    { code: "535.4", desc: "Interferência. Difracção" },
    { code: "535.5", desc: "Polarização. Dupla Refracção" },
    { code: "535.6", desc: "Cores e suas propriedades" },
    { code: "535.8", desc: "Aplicações da óptica em geral" },
    { code: "536", desc: "Calor. Termodinâmica. Física estatística" },
    { code: "536.1", desc: "Teoria geral do calor" },
    { code: "536.2", desc: "Condução de calor. Transferência" },
    { code: "536.5", desc: "Temperatura. Escalas. Termómetros" },
    { code: "536.6", desc: "Medição da quantidade de calor. Calorimetria" },
    { code: "536.7", desc: "Termodinâmica. Energética" },
    { code: "537", desc: "Electricidade. Magnetismo. Electromagnetismo" },
    { code: "537.2", desc: "Electricidade estática. Electroestática" },
    { code: "537.3", desc: "Corrente eléctrica. Electrocinética" },
    { code: "537.5", desc: "Fenómenos do electrão e do ião" },
    { code: "537.8", desc: "Electromagnetismo. Campo electromagnético. Electrodinâmica" },
    { code: "538.9", desc: "Física da matéria condensada. Estado sólido" },
    { code: "539", desc: "Natureza física da matéria. Física atómica e molecular" },
    { code: "539.3", desc: "Elasticidade. Deformação" },
    { code: "539.4", desc: "Força. Resistência à tensão" },
    { code: "539.5", desc: "Propriedades que afectam a deformabilidade" },
    { code: "54", desc: "Química. Cristalografia. Mineralogia" },
    { code: "542", desc: "Química prática de laboratório" },
    { code: "543", desc: "Química analítica" },
    { code: "543.3", desc: "Amostragem e análise da água" },
    { code: "544", desc: "Química física" },
    { code: "546", desc: "Química inorgânica" },
    { code: "547", desc: "Química orgânica" },
    { code: "548", desc: "Cristalografia" },
    { code: "549", desc: "Mineralogia" },
    { code: "55", desc: "Ciências da terra. Ciências geológicas" },
    { code: "550", desc: "Ciências auxiliares da geologia" },
    { code: "550.3", desc: "Geofísica" },
    { code: "550.4", desc: "Geoquímica" },
    { code: "551", desc: "Geologia geral. Meteorologia. Geologia histórica" },
    { code: "552", desc: "Petrologia. Petrografia" },
    { code: "553", desc: "Geologia económica. Depósitos minerais" },
    { code: "556", desc: "Hidrosfera. Água em geral. Hidrologia" },
    { code: "56", desc: "Paleontologia" },
    { code: "57", desc: "Ciências biológicas em geral" },
    { code: "572", desc: "Antropologia física" },
    { code: "574", desc: "Ecologia geral e biodiversidade" },
    { code: "575", desc: "Genética geral" },
    { code: "576", desc: "Biologia celular. Citologia" },
    { code: "577", desc: "Bases materiais da vida. Bioquímica. Biofísica" },
    { code: "578", desc: "Virologia" },
    { code: "579", desc: "Microbiologia" },
    { code: "58", desc: "Botânica" },
    { code: "581", desc: "Botânica geral" },
    { code: "581.1", desc: "Fisiologia vegetal" },
    { code: "581.2", desc: "Fitopatologia" },
    { code: "581.4", desc: "Morfologia vegetal" },
    { code: "582", desc: "Botânica sistemática" },
    { code: "59", desc: "Zoologia" },
    { code: "591", desc: "Zoologia geral" },
    { code: "592", desc: "Invertebrados" },
    { code: "595.7", desc: "Insectos" },
    { code: "597", desc: "Peixes" },
    { code: "598.1", desc: "Répteis" },
    { code: "598.2", desc: "Aves" },
    { code: "599", desc: "Mamíferos" },

    // --- CLASSE 6: CIÊNCIAS APLICADAS ---
    { code: "60", desc: "Biotecnologia" },
    { code: "61", desc: "Ciências médicas" },
    { code: "611", desc: "Anatomia humana" },
    { code: "612", desc: "Fisiologia humana" },
    { code: "613", desc: "Higiene em geral. Saúde pessoal" },
    { code: "614", desc: "Saúde e higiene públicas" },
    { code: "615", desc: "Farmacologia. Terapêutica" },
    { code: "616", desc: "Patologia. Medicina clínica" },
    { code: "62", desc: "Engenharia. Tecnologia em geral" },
    { code: "621", desc: "Engenharia mecânica. Maquinaria" },
    { code: "621.3", desc: "Engenharia eléctrica" },
    { code: "622", desc: "Mineração" },
    { code: "623", desc: "Engenharia militar" },
    { code: "624", desc: "Engenharia civil" },
    { code: "625", desc: "Engenharia ferroviária e rodoviária" },
    { code: "626", desc: "Engenharia hidráulica" },
    { code: "628", desc: "Engenharia sanitária. Água. Iluminação" },
    { code: "629", desc: "Engenharia de veículos de transporte" },
    { code: "63", desc: "Agricultura. Silvicultura" },
    { code: "630", desc: "Silvicultura" },
    { code: "631", desc: "Agricultura em geral" },
    { code: "64", desc: "Economia doméstica. Ciência doméstica" },
    { code: "65", desc: "Indústrias da comunicação e dos transportes. Contabilidade" },
    { code: "657", desc: "Contabilidade" },
    { code: "658", desc: "Gestão, administração de empresas" },
    { code: "659", desc: "Publicidade. Relações públicas" },
    { code: "66", desc: "Tecnologia química" },
    { code: "67", desc: "Indústria, artes industriais e ofícios diversos" },
    { code: "68", desc: "Indústrias, artes e ofícios de artigos acabado" },
    { code: "69", desc: "Indústria da construção" },

    // --- CLASSE 7: ARTE ---
    { code: "7.01", desc: "Teoria e filosofia da arte" },
    { code: "7.02", desc: "Técnicas artísticas" },
    { code: "7.03", desc: "Períodos e fases artísticas" },
    { code: "71", desc: "Planeamento territorial. Paisagens. Parques" },
    { code: "72", desc: "Arquitectura" },
    { code: "73", desc: "Artes plásticas" },
    { code: "74", desc: "Desenho. Design. Artes e ofícios aplicados" },
    { code: "75", desc: "Pintura" },
    { code: "76", desc: "Artes gráficas. Gravura" },
    { code: "77", desc: "Fotografia e processos similares" },
    { code: "78", desc: "Música" },
    { code: "79", desc: "DIVERTIMENTOS. ESPECTÁCULOS. JOGOS. DESPORTOS" },
    { code: "791", desc: "Cinema. Filmes" },
    { code: "792", desc: "Teatro. Representação teatral" },
    { code: "796", desc: "Desporto. Jogos. Exercícios físicos" },

    // --- CLASSE 8: LÍNGUA ---
    { code: "80", desc: "Questões gerais referentes à linguística e à literatura" },
    { code: "801", desc: "Prosódia. Ciências auxiliares da filologia" },
    { code: "81", desc: "Linguística e línguas" },
    { code: "811.111", desc: "Inglês" },
    { code: "811.112.2", desc: "Alemão" },
    { code: "811.131.1", desc: "Italiano" },
    { code: "811.133.1", desc: "Francês" },
    { code: "811.134.2", desc: "Espanhol" },
    { code: "811.134.3", desc: "Português" },
    { code: "82", desc: "Literatura" },
    { code: "82-1", desc: "Poesia. Poemas" },
    { code: "82-2", desc: "Drama. Peças de teatro" },
    { code: "82-3", desc: "Ficção. Prosa narrativa" },
    { code: "821.111", desc: "Literatura inglesa" },
    { code: "821.134.3", desc: "Literatura portuguesa" },

    // --- CLASSE 9: GEOGRAFIA ---
    { code: "902", desc: "Arqueologia" },
    { code: "903", desc: "Pré-história" },
    { code: "908", desc: "Estudos regionais" },
    { code: "91", desc: "Geografia. Viagens" },
    { code: "929", desc: "Estudos biográficos. Genealogia. Heráldica" },
    { code: "930", desc: "Ciência histórica. Historiografia" },
    { code: "94", desc: "História em geral" }
];
